In [16]:
import pandas as pd

df = pd.read_csv("disease_symptoms.csv")

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (5251, 2)

Columns:
['disease', 'symptom']

First 5 rows:

               disease                                            symptom
0  Atrial fibrillation  Sensations of a fast, fluttering or pounding h...
1  Atrial fibrillation                                         Chest pain
2  Atrial fibrillation                                          Dizziness
3  Atrial fibrillation                                            Fatigue
4  Atrial fibrillation                                    Lightheadedness

In [15]:
df1 = pd.read_csv("disease_doctor.csv")
df2 = pd.read_csv("disease_info_clean.csv")

In [2]:
print("عدد الأمراض الفعلي:")
print(df["disease"].nunique())

print("\nأول 20 مرض:")
for d in df["disease"].dropna().unique()[:20]:
    print(d)

عدد الأمراض الفعلي:
724

أول 20 مرض:
Atrial fibrillation
Abdominal aortic aneurysm
Separated shoulder
Acanthosis nigricans
Achilles tendinitis
Gastroesophageal reflux disease (GERD)
ACL injury
HIV/AIDS
Actinic keratosis
Acute coronary syndrome
Sweet's syndrome
Acute flaccid myelitis (AFM)
Acute myelogenous leukemia
Guillain-Barre syndrome
Acute kidney failure
Acute lymphocytic leukemia
Acute sinusitis
Alcohol use disorder
Drug addiction (substance use disorder)
Nicotine dependence

In [9]:
print(df[["disease", "overview", "treatment", "when_to_see_doctor"]].isnull().sum())

disease               0
overview              0
treatment             0
when_to_see_doctor    0
dtype: int64

In [11]:
sample_row = df.iloc[0]

print("Disease:\n", sample_row["disease"])

print("\nOverview:\n", sample_row["overview"])
print("\nTreatment:\n", sample_row["treatment"])
print("\nWhen to see doctor:\n", sample_row["when_to_see_doctor"])

Disease:
 Atrial fibrillation

Overview:
 In a typical heart rhythm, a tiny cluster of cells at the sinus node sends out an electrical signal (sinus node impulse). The signal follows a specific path through the upper chambers (atria) and into the lower chambers (ventricles), causing them to squeeze and pump out blood. In atrial fibrillation, electrical signals fire from many areas in the atria, causing the chambers to beat chaotically. Some or all of these chaotic signals enter the ventricles, causing a fast, irregular heartbeat. In a typical heart rhythm, a tiny cluster of cells at the sinus node sends out an electrical signal (sinus node impulse). The signal follows a specific path through the upper chambers (atria) and into the lower chambers (ventricles), causing them to squeeze and pump out blood. In atrial fibrillation, electrical signals fire from many areas in the atria, causing the chambers to beat chaotically. Some or all of these chaotic signals enter the ventricles, causing a fast, irregular heartbeat. Atrial fibrillation (A-fib) is an irregular and often very rapid heart rhythm (arrhythmia) that can lead to blood clots in the heart. A-fib increases the risk of stroke, heart failure and other heart-related complications. During atrial fibrillation, the heart's upper chambers (the atria) beat chaotically and irregularly — out of sync with the lower chambers (the ventricles) of the heart. For many people, A-fib may have no symptoms. However, A-fib may cause a fast, pounding heartbeat (palpitations), shortness of breath or weakness. Episodes of atrial fibrillation may come and go, or they may be persistent. Although A-fib itself usually isn't life-threatening, it's a serious medical condition that requires proper treatment to prevent stroke. Treatment for atrial fibrillation may include medications, therapy to reset the heart rhythm and catheter procedures to block faulty heart signals. A person with atrial fibrillation may also have a related heart rhythm problem called atrial flutter. Although atrial flutter is a different arrhythmia, the treatment is quite similar to atrial fibrillation.

Treatment:
 Reset the heart rhythm Control the heart rate Prevent blood clots that can lead to stroke Medications Therapy to reset the heart rhythm (cardioversion) Surgery or catheter procedures

When to see doctor:
 If you have any signs or symptoms of atrial fibrillation, make an appointment with your doctor. If you have chest pain, seek immediate medical help. Chest pain could mean that you're having a heart attack.

In [17]:
sample_row = df.iloc[0]

print("Disease:\n", sample_row["disease"])
print("\nSymptoms:\n", sample_row["symptom"])

Disease:
 Atrial fibrillation

Symptoms:
 Sensations of a fast, fluttering or pounding heartbeat (palpitations)

In [18]:
df["symptom_list"] = df["symptom"].apply(lambda x: [s.strip() for s in x.split("|") if s.strip() != ""])

In [19]:
for i in range(5):
    print("Disease:", df.iloc[i]["disease"])
    print("Symptoms list:", df.iloc[i]["symptom_list"])
    print("-" * 80)

Disease: Atrial fibrillation
Symptoms list: ['Sensations of a fast, fluttering or pounding heartbeat (palpitations)']
--------------------------------------------------------------------------------
Disease: Atrial fibrillation
Symptoms list: ['Chest pain']
--------------------------------------------------------------------------------
Disease: Atrial fibrillation
Symptoms list: ['Dizziness']
--------------------------------------------------------------------------------
Disease: Atrial fibrillation
Symptoms list: ['Fatigue']
--------------------------------------------------------------------------------
Disease: Atrial fibrillation
Symptoms list: ['Lightheadedness']
--------------------------------------------------------------------------------

In [20]:
rows = []

for _, row in df.iterrows():
    disease = row["disease"]
    for symptom in row["symptom_list"]:
        rows.append({
            "disease": disease,
            "symptom": symptom
        })

symptoms_df = pd.DataFrame(rows)

print(symptoms_df.shape)
display(symptoms_df.head(20))

(5251, 2)

,disease,symptom
0,Atrial fibrillation,"Sensations of a fast, fluttering or pounding h..."
1,Atrial fibrillation,Chest pain
2,Atrial fibrillation,Dizziness
3,Atrial fibrillation,Fatigue
4,Atrial fibrillation,Lightheadedness
5,Atrial fibrillation,Reduced ability to exercise
6,Atrial fibrillation,Shortness of breath
7,Atrial fibrillation,Weakness
8,Atrial fibrillation,Occasional (paroxysmal atrial fibrillation). A...
9,Atrial fibrillation,Persistent. With this type of atrial fibrillat...
10,Atrial fibrillation,Long-standing persistent. This type of atrial ...
11,Atrial fibrillation,Permanent. In this type of atrial fibrillation...
12,Abdominal aortic aneurysm,"Deep, constant pain in the belly area or side ..."
13,Abdominal aortic aneurysm,Back pain
14,Abdominal aortic aneurysm,A pulse near the bellybutton
15,Separated shoulder,Shoulder pain
16,Separated shoulder,Shoulder or arm weakness
17,Separated shoulder,Shoulder bruising or swelling
18,Separated shoulder,Limited shoulder movement
19,Separated shoulder,A bump and swelling at the top of your shoulder

In [21]:
symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(str(x).split()))

print(symptoms_df["word_count"].describe())

display(symptoms_df.sort_values("word_count", ascending=False).head(20))

count    5251.000000
mean        8.076176
std        10.092539
min         1.000000
25%         2.000000
50%         5.000000
75%        10.000000
max       119.000000
Name: word_count, dtype: float64

,disease,symptom,word_count
2272,Narcolepsy,Sleep paralysis. People with narcolepsy often ...,119
482,Sickle cell anemia,"Episodes of pain. Periodic episodes of pain, c...",113
2271,Narcolepsy,"Sudden loss of muscle tone. This condition, ca...",99
3900,Measles,Acute illness and rash. The rash consists of s...,93
2107,Coronary artery disease,Heart attack. A completely blocked coronary ar...,91
1638,Carpal tunnel syndrome,Tingling or numbness. You may notice tingling ...,90
3822,Lyme disease,Rash. From three to 30 days after an infected ...,89
2270,Narcolepsy,Excessive daytime sleepiness. People with narc...,85
3352,Herniated disk,Arm or leg pain. If your herniated disk is in ...,81
1092,Blood in urine (hematuria),Enlarged prostate. The prostate gland — which ...,80
1091,Blood in urine (hematuria),A bladder or kidney stone. The minerals in con...,79
2560,Foot drop,Nerve injury. The most common cause of foot dr...,77
2105,Coronary artery disease,Chest pain (angina). You may feel pressure or ...,76
139,Alcohol use disorder,Alcohol intoxication results as the amount of ...,74
1098,Blood in urine (hematuria),Strenuous exercise. It's rare for strenuous ex...,73
4318,Perimenopause,Irregular periods. As ovulation becomes more u...,72
140,Alcohol use disorder,Alcohol withdrawal can occur when alcohol use ...,70
1690,Stroke,"Paralysis or numbness of the face, arm or leg....",70
3031,Frostbite,Deep (severe) frostbite. As frostbite progress...,70
1756,Cholera,Dehydration. Dehydration can develop within ho...,69

In [22]:
clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].copy()

print("عدد الصفوف:", clean_df.shape)
print("عدد الأمراض:", clean_df["disease"].nunique())

عدد الصفوف: (3160, 3)
عدد الأمراض: 597

In [23]:
clean_df = clean_df.drop_duplicates()

In [24]:
disease_counts = clean_df["disease"].value_counts()

display(disease_counts.head(20))

disease
Coronavirus disease 2019 (COVID-19)     30
Prescription drug abuse                 29
Fetal alcohol syndrome                  23
Concussion                              17
Intermittent explosive disorder         16
Hypothyroidism (underactive thyroid)    15
Anorexia nervosa                        15
Hashimoto's disease                     15
Pediatric obstructive sleep apnea       14
Krabbe disease                          14
Panic attacks and panic disorder        13
Rabies                                  13
Celiac disease                          13
Dengue fever                            13
Allergies                               13
Serotonin syndrome                      13
Ehrlichiosis and anaplasmosis           12
Scorpion sting                          12
Malaria                                 12
Naegleria infection                     12
Name: count, dtype: int64

In [25]:
symptoms_df = pd.read_csv("disease_symptoms.csv")

print(symptoms_df.shape)
print(symptoms_df.head())

(5251, 2)
               disease                                            symptom
0  Atrial fibrillation  Sensations of a fast, fluttering or pounding h...
1  Atrial fibrillation                                         Chest pain
2  Atrial fibrillation                                          Dizziness
3  Atrial fibrillation                                            Fatigue
4  Atrial fibrillation                                    Lightheadedness

In [26]:
symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(str(x).split()))

clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].copy()

In [29]:
symptom_texts = clean_df["symptom"].tolist()
symptom_embeddings = embed_model.encode(symptom_texts)

print("Embeddings shape:", symptom_embeddings.shape)

Embeddings shape: (3160, 384)

In [28]:
from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

print("Embedding model loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding model loaded

In [30]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

In [31]:
symptoms_df = pd.read_csv("disease_symptoms.csv")

In [32]:
symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(str(x).split()))

clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].copy()

In [33]:
embed_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [34]:
symptom_texts = clean_df["symptom"].tolist()
symptom_embeddings = embed_model.encode(symptom_texts)

In [2]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

symptoms_df = pd.read_csv("disease_symptoms.csv")
info_df = pd.read_csv("disease_info_clean.csv")
doctor_df = pd.read_csv("disease_doctor.csv")

In [36]:
def predict_disease(user_input, top_k=10):

    query = embed_model.encode([user_input])

    similarities = np.dot(symptom_embeddings, query.T).reshape(-1)

    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}

    for i in top_idx:
        disease = clean_df.iloc[i]["disease"]
        score = similarities[i]

        disease_scores[disease] = disease_scores.get(disease, 0) + score

    sorted_diseases = sorted(
        disease_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return sorted_diseases[:3]

In [46]:
def get_disease_info(disease):

    row = info_df[info_df["disease"] == disease]

    if len(row) == 0:
        return None

    row = row.iloc[0]

    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

In [50]:
def get_doctor(disease):

    row = doctor_df[doctor_df["disease"] == disease]

    if len(row) == 0:
        return "طبيب عام"

    return row.iloc[0]["doctor_specialty"]

In [51]:
def chatbot(user_input):

    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض."

    best_disease = predictions[0][0]

    info = get_disease_info(best_disease)

    doctor = get_doctor(best_disease)

    response = "الأمراض المحتملة:\n\n"

    for i,(d,score) in enumerate(predictions):
        response += f"{i+1}️⃣ {d}\n"

    response += "\n----------------\n\n"

    response += f"التشخيص الأكثر احتمالاً:\n{best_disease}\n\n"

    if info:
        response += f"شرح المرض:\n{info['overview']}\n\n"
        response += f"لتقليل الأعراض:\n{info['treatment']}\n\n"
        response += f"متى يجب زيارة الطبيب؟\n{info['when']}\n\n"

    response += f"التخصص المناسب:\n{doctor}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [52]:
while True:

    user = input("اكتب الأعراض: ")

    if user == "exit":
        break

    print(chatbot(user))

اكتب الأعراض:  بطني بتولع بعد الاكل

الأمراض المحتملة:

1️⃣ Typhoid fever
2️⃣ Tonsillitis
3️⃣ Heart failure

----------------

التشخيص الأكثر احتمالاً:
Typhoid fever

شرح المرض:
Typhoid fever is caused by Salmonella typhi bacteria. Typhoid fever is rare in developed countries. It is still a serious health threat in the developing world, especially for children. Contaminated food and water or close contact with an infected person cause typhoid fever. Signs and symptoms usually include: Most people who have typhoid fever feel better a few days after they start antibiotic treatment, but a small number of them may die of complications. Vaccines against typhoid fever are only partially effective. Vaccines usually are reserved for those who may be exposed to the disease or who are traveling to areas where typhoid fever is common.

لتقليل الأعراض:
Ciprofloxacin (Cipro). In the United States, doctors often prescribe this for adults who aren't pregnant. Another similar drug called ofloxacin also may be used. Unfortunately, many Salmonella typhi bacteria are no longer susceptible to antibiotics of this type, particularly strains picked up in Southeast Asia. Azithromycin (Zithromax). This may be used if a person is unable to take ciprofloxacin or the bacteria are resistant to ciprofloxacin. Ceftriaxone. This injectable antibiotic is an alternative in more-complicated or serious infections and for people who may not be candidates for ciprofloxacin, such as children.

متى يجب زيارة الطبيب؟
See a doctor immediately if you think you might have typhoid fever. If you live in the United States and become sick while traveling in a foreign country, call the U.S. Consulate for a list of doctors. If you have signs and symptoms after you return home, consider seeing a doctor who focuses on international travel medicine or infectious diseases. A doctor who is familiar with these areas may be able to recognize and treat your illness more quickly.

التخصص المناسب:
General Physician

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

اكتب الأعراض:  end

الأمراض المحتملة:

1️⃣ Dumping syndrome
2️⃣ Stress incontinence
3️⃣ Progressive supranuclear palsy

----------------

التشخيص الأكثر احتمالاً:
Dumping syndrome

شرح المرض:
Dumping syndrome is a condition that can develop after surgery to remove all or part of your stomach or after surgery to bypass your stomach to help you lose weight. The condition can also develop in people who have had esophageal surgery. Also called rapid gastric emptying, dumping syndrome occurs when food, especially sugar, moves from your stomach into your small bowel too quickly. Most people with dumping syndrome develop signs and symptoms, such as abdominal cramps and diarrhea, 10 to 30 minutes after eating. Other people have symptoms one to three hours after eating, and still others have both early and late symptoms. Generally, you can help prevent dumping syndrome by changing your diet after surgery. Changes might include eating smaller meals and limiting high-sugar foods. In more-serious cases of dumping syndrome, you may need medications or surgery.

لتقليل الأعراض:
Eat smaller meals. Try eating five or six small meals a day rather than three larger ones. Drink most of your fluids between meals. At first, don't drink anything for 30 to 60 minutes before and after meals. Drink 6 to 8 cups  (1.4 to 1.9 liters) of fluids a day. At first, limit fluid with meals to 1/2 cup (118 milliliters). Increase fluid with meals as you tolerate it.
Change your diet. Eat more protein — meat, poultry, creamy peanut butter and fish — and complex carbohydrates — oatmeal and other whole-grain foods high in fiber. Limit high-sugar foods, such as candy, table sugar, syrup, sodas and juices.
The natural sugar in dairy products (lactose) might worsen your symptoms. Try small amounts at first, or eliminate them if you think they're causing problems. You might want to see a registered dietitian for more advice about what to eat.
 Increase fiber intake. Psyllium, guar gum and pectin in food or supplements can delay the absorption of carbohydrates in the small intestine. Check with your doctor about drinking alcohol.

متى يجب زيارة الطبيب؟
Contact your doctor if any of the following apply to you.
You develop signs and symptoms that might be due to dumping syndrome, even if you haven't had surgery.
Your symptoms are not controlled by dietary changes.
You are losing large amounts of weight due to dumping syndrome. Your doctor may refer you to a registered dietitian to help you create an eating plan.
 Causes

التخصص المناسب:
General Physician

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

اكتب الأعراض:  ecit

الأمراض المحتملة:

1️⃣ Dumping syndrome
2️⃣ Intermittent explosive disorder
3️⃣ Rheumatoid arthritis

----------------

التشخيص الأكثر احتمالاً:
Dumping syndrome

شرح المرض:
Dumping syndrome is a condition that can develop after surgery to remove all or part of your stomach or after surgery to bypass your stomach to help you lose weight. The condition can also develop in people who have had esophageal surgery. Also called rapid gastric emptying, dumping syndrome occurs when food, especially sugar, moves from your stomach into your small bowel too quickly. Most people with dumping syndrome develop signs and symptoms, such as abdominal cramps and diarrhea, 10 to 30 minutes after eating. Other people have symptoms one to three hours after eating, and still others have both early and late symptoms. Generally, you can help prevent dumping syndrome by changing your diet after surgery. Changes might include eating smaller meals and limiting high-sugar foods. In more-serious cases of dumping syndrome, you may need medications or surgery.

لتقليل الأعراض:
Eat smaller meals. Try eating five or six small meals a day rather than three larger ones. Drink most of your fluids between meals. At first, don't drink anything for 30 to 60 minutes before and after meals. Drink 6 to 8 cups  (1.4 to 1.9 liters) of fluids a day. At first, limit fluid with meals to 1/2 cup (118 milliliters). Increase fluid with meals as you tolerate it.
Change your diet. Eat more protein — meat, poultry, creamy peanut butter and fish — and complex carbohydrates — oatmeal and other whole-grain foods high in fiber. Limit high-sugar foods, such as candy, table sugar, syrup, sodas and juices.
The natural sugar in dairy products (lactose) might worsen your symptoms. Try small amounts at first, or eliminate them if you think they're causing problems. You might want to see a registered dietitian for more advice about what to eat.
 Increase fiber intake. Psyllium, guar gum and pectin in food or supplements can delay the absorption of carbohydrates in the small intestine. Check with your doctor about drinking alcohol.

متى يجب زيارة الطبيب؟
Contact your doctor if any of the following apply to you.
You develop signs and symptoms that might be due to dumping syndrome, even if you haven't had surgery.
Your symptoms are not controlled by dietary changes.
You are losing large amounts of weight due to dumping syndrome. Your doctor may refer you to a registered dietitian to help you create an eating plan.
 Causes

التخصص المناسب:
General Physician

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

اكتب الأعراض:  ثءهف

الأمراض المحتملة:

1️⃣ Intermittent explosive disorder
2️⃣ Tinnitus
3️⃣ Stress incontinence

----------------

التشخيص الأكثر احتمالاً:
Intermittent explosive disorder

شرح المرض:
Intermittent explosive disorder involves repeated, sudden episodes of impulsive, aggressive, violent behavior or angry verbal outbursts in which you react grossly out of proportion to the situation. Road rage, domestic abuse, throwing or breaking objects, or other temper tantrums may be signs of intermittent explosive disorder. These intermittent, explosive outbursts cause you significant distress, negatively impact your relationships, work and school, and they can have legal and financial consequences. Intermittent explosive disorder is a chronic disorder that can continue for years, although the severity of outbursts may decrease with age. Treatment involves medications and psychotherapy to help you control your aggressive impulses.

لتقليل الأعراض:
Identify which situations or behaviors may trigger an aggressive response Learn how to manage anger and control inappropriate responses using techniques such as relaxation training, thinking differently about situations (cognitive restructuring), and applying communication and problem-solving skills

متى يجب زيارة الطبيب؟
If you recognize your own behavior in the description of intermittent explosive disorder, talk with your doctor about treatment options or ask for a referral to a mental health professional.

التخصص المناسب:
General Physician

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

اكتب الأعراض:  exit

In [45]:
print(info_df.columns)

Index(['disease', 'overview', 'treatment', 'when_to_see_doctor'], dtype='object')

In [53]:
arabic_map = {
    "بطني بتولع": "heartburn acid reflux",
    "بطني بتحرق": "heartburn acid reflux",
    "حموضة": "heartburn acid reflux",
    "حرقان في المعدة": "heartburn acid reflux",
    "حرقان بعد الاكل": "heartburn acid reflux",
    "بعد الاكل": "after eating",

    "كحة": "cough",
    "كحه": "cough",
    "سخونية": "fever",
    "سخونيه": "fever",
    "حرارة": "fever",
    "حراره": "fever",

    "صداع": "headache",
    "دوخة": "dizziness",
    "دوخه": "dizziness",
    "غثيان": "nausea",
    "قيء": "vomiting",
    "ترجيع": "vomiting",

    "وجع بطن": "abdominal pain",
    "ألم بطن": "abdominal pain",
    "مغص": "abdominal pain",

    "حرقان في البول": "burning urination",
    "كثرة التبول": "frequent urination",

    "رشح": "runny nose",
    "احتقان": "nasal congestion",
    "التهاب الحلق": "sore throat",
}

In [54]:
def normalize_arabic(user_input):
    text = str(user_input).strip().lower()
    extra = []

    for k, v in arabic_map.items():
        if k in text:
            extra.append(v)

    if extra:
        return text + " " + " ".join(extra)

    return text

In [55]:
from sentence_transformers import SentenceTransformer
import numpy as np

embed_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

symptom_texts = clean_df["symptom"].tolist()
symptom_embeddings = embed_model.encode(symptom_texts)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [56]:
def predict_disease(user_input, top_k=12):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}

    for i in top_idx:
        disease = clean_df.iloc[i]["disease"]
        symptom = clean_df.iloc[i]["symptom"]
        score = float(similarities[i])

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    return ranked[:3]

In [57]:
results = predict_disease("بطني بتولع بعد الاكل")

for disease, data in results:
    print("Disease:", disease)
    print("Score:", data["score"])
    print("Matched symptoms:", data["matched_symptoms"][:5])
    print("-" * 50)

Disease: Peptic ulcer
Score: 31.87263584136963
Matched symptoms: ['Heartburn', 'Burning stomach pain', 'Intolerance to fatty foods']
--------------------------------------------------
Disease: Stomach cancer
Score: 22.5825834274292
Matched symptoms: ['Heartburn', 'Feeling bloated after eating']
--------------------------------------------------
Disease: Hiatal hernia
Score: 13.171442985534668
Matched symptoms: ['Heartburn']
--------------------------------------------------

In [58]:
def get_disease_info(disease):
    row = info_df[info_df["disease"] == disease]
    if len(row) == 0:
        return None
    row = row.iloc[0]
    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

def get_doctor(disease):
    row = doctor_df[doctor_df["disease"] == disease]
    if len(row) == 0:
        return "General Physician"
    return row.iloc[0]["doctor"]

def chatbot(user_input):
    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض."

    best_disease = predictions[0][0]
    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    response = "الأمراض المحتملة:\n\n"
    for i, (d, data) in enumerate(predictions, start=1):
        response += f"{i}️⃣ {d}\n"

    response += "\n----------------\n\n"
    response += f"التشخيص الأكثر احتمالاً:\n{best_disease}\n\n"

    if info:
        response += f"شرح المرض:\n{info['overview']}\n\n"
        response += f"لتقليل الأعراض:\n{info['treatment']}\n\n"
        response += f"متى يجب زيارة الطبيب؟\n{info['when']}\n\n"

    response += f"التخصص المناسب:\n{doctor}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [59]:
results = predict_disease("بطني بتولع بعد الاكل")
for disease, data in results:
    print(disease, data["matched_symptoms"][:5], data["score"])

Peptic ulcer ['Heartburn', 'Burning stomach pain', 'Intolerance to fatty foods'] 31.87263584136963
Stomach cancer ['Heartburn', 'Feeling bloated after eating'] 22.5825834274292
Hiatal hernia ['Heartburn'] 13.171442985534668

In [60]:
print("GERD in clean_df?:", "Gastroesophageal reflux disease (GERD)" in clean_df["disease"].unique())
print(clean_df[clean_df["disease"] == "Gastroesophageal reflux disease (GERD)"][["disease","symptom"]].head(20))

GERD in clean_df?: True
                                   disease  \
31  Gastroesophageal reflux disease (GERD)
32  Gastroesophageal reflux disease (GERD)
33  Gastroesophageal reflux disease (GERD)
35  Gastroesophageal reflux disease (GERD)
36  Gastroesophageal reflux disease (GERD)
37  Gastroesophageal reflux disease (GERD)
38  Gastroesophageal reflux disease (GERD)

                                 symptom
31                            Chest pain
32                 Difficulty swallowing
33  Regurgitation of food or sour liquid
35                         Chronic cough
36                            Laryngitis
37               New or worsening asthma
38                       Disrupted sleep

In [61]:
gerd_rows = clean_df[clean_df["disease"] == "Gastroesophageal reflux disease (GERD)"]
print("عدد أعراض GERD:", len(gerd_rows))
for s in gerd_rows["symptom"].tolist():
    print(s)

عدد أعراض GERD: 7
Chest pain
Difficulty swallowing
Regurgitation of food or sour liquid
Chronic cough
Laryngitis
New or worsening asthma
Disrupted sleep

In [62]:
heartburn_rows = clean_df[clean_df["symptom"].str.lower() == "heartburn"]
print(heartburn_rows[["disease","symptom"]])

             disease    symptom
1368  Stomach cancer  Heartburn
2853     Esophagitis  Heartburn
3338   Hiatal hernia  Heartburn
4309    Peptic ulcer  Heartburn

In [63]:
import pandas as pd

symptoms_df = pd.read_csv("disease_symptoms.csv")
symptoms_df.columns = symptoms_df.columns.str.strip().str.lower()

print("Shape:", symptoms_df.shape)
print("عدد الأمراض:", symptoms_df["disease"].nunique())

symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(str(x).split()))

clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].drop_duplicates().copy()

print("بعد تنظيف الأعراض القصيرة:")
print("Shape:", clean_df.shape)
print("عدد الأمراض:", clean_df["disease"].nunique())

disease_counts = clean_df.groupby("disease")["symptom"].count().sort_values(ascending=False)

print("\nأعلى 30 مرض من حيث عدد الأعراض:")
print(disease_counts.head(30))

Shape: (5251, 2)
عدد الأمراض: 724
بعد تنظيف الأعراض القصيرة:
Shape: (3148, 3)
عدد الأمراض: 597

أعلى 30 مرض من حيث عدد الأعراض:
disease
Coronavirus disease 2019 (COVID-19)                      30
Prescription drug abuse                                  29
Fetal alcohol syndrome                                   23
Concussion                                               17
Intermittent explosive disorder                          16
Hashimoto's disease                                      15
Anorexia nervosa                                         15
Hypothyroidism (underactive thyroid)                     15
Pediatric obstructive sleep apnea                        14
Krabbe disease                                           14
Panic attacks and panic disorder                         13
Allergies                                                13
Serotonin syndrome                                       13
Dengue fever                                             13
Celiac disease                                           13
Rabies                                                   13
Scorpion sting                                           12
Naegleria infection                                      12
Vaginal atrophy                                          12
Encephalitis                                             12
Ehrlichiosis and anaplasmosis                            12
Malaria                                                  12
Adult attention-deficit/hyperactivity disorder (ADHD)    12
Coarctation of the aorta                                 11
Progeria                                                 11
H1N1 flu (swine flu)                                     11
Peritonitis                                              11
Chagas disease                                           11
Hemochromatosis                                          11
Childhood schizophrenia                                  11
Name: symptom, dtype: int64

In [64]:
top_150 = disease_counts.head(150).reset_index()
top_150.columns = ["disease", "symptom_count"]
top_150.to_csv("top_150_diseases.csv", index=False)

print("saved top_150_diseases.csv")

saved top_150_diseases.csv

In [65]:
top_150 = disease_counts.head(150).index

filtered_df = clean_df[clean_df["disease"].isin(top_150)].copy()

print(filtered_df["disease"].nunique())

150

In [66]:
remove_diseases = [
    "Krabbe disease",
    "Progeria",
    "Naegleria infection",
    "Coarctation of the aorta",
    "Childhood schizophrenia"
]

filtered_df = filtered_df[~filtered_df["disease"].isin(remove_diseases)]

In [67]:
print("عدد الأمراض النهائي:", filtered_df["disease"].nunique())

عدد الأمراض النهائي: 145

In [68]:
pip install pandas numpy sentence-transformers deep-translator

Requirement already satisfied: pandas in c:\neural\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\neural\lib\site-packages (1.26.4)
Requirement already satisfied: sentence-transformers in c:\neural\lib\site-packages (5.2.3)
Requirement already satisfied: deep-translator in c:\neural\lib\site-packages (1.11.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\menna\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\neural\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\neural\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\neural\lib\site-packages (from sentence-transformers) (5.2.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\neural\lib\site-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in c:\neural\lib\site-packages (from sentence-transformers) (2.9.1)
Requirement already satisfied: scikit-learn in c:\neural\lib\site-packages (from sentence-transformers) (1.5.1)
Requirement already satisfied: scipy in c:\neural\lib\site-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\neural\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in c:\neural\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: packaging>=20.0 in c:\users\menna\appdata\roaming\python\python312\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\neural\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\neural\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\neural\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in c:\neural\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\neural\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\neural\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\neural\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\neural\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\neural\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: typer in c:\neural\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.21.1)
Requirement already satisfied: anyio in c:\neural\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in c:\neural\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\neural\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\neural\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2.10)
Requirement already satisfied: h11>=0.16 in c:\neural\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\neural\lib\site-packages (from deep-translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\neural\lib\site-packages (from deep-translator) (2.32.5)
Requirement already satisfied: soupsieve>1.2 in c:\neural\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\neural\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\neural\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: six>=1.5 in c:\users\menna\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sympy>=1.13.3 in c:\neural\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\neural\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in c:\neural\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\neural\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\neural\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\menna\appdata\roaming\python\python312\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\neural\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\neural\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: joblib>=1.2.0 in c:\neural\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\neural\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: click>=8.0.0 in c:\neural\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\neural\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\neural\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\neural\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\menna\appdata\roaming\python\python312\site-packages (from rich>=10.11.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\neural\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [69]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from deep_translator import GoogleTranslator

symptoms_df = pd.read_csv("disease_symptoms.csv")
info_df = pd.read_csv("disease_info_clean.csv")
doctor_df = pd.read_csv("disease_doctor.csv")

symptoms_df.columns = symptoms_df.columns.str.strip().str.lower()
info_df.columns = info_df.columns.str.strip().str.lower()
doctor_df.columns = doctor_df.columns.str.strip().str.lower()

print("symptoms_df:", symptoms_df.shape)
print("info_df:", info_df.shape)
print("doctor_df:", doctor_df.shape)

print(symptoms_df.head())
print(info_df.head())
print(doctor_df.head())

symptoms_df: (5251, 2)
info_df: (724, 4)
doctor_df: (724, 2)
               disease                                            symptom
0  Atrial fibrillation  Sensations of a fast, fluttering or pounding h...
1  Atrial fibrillation                                         Chest pain
2  Atrial fibrillation                                          Dizziness
3  Atrial fibrillation                                            Fatigue
4  Atrial fibrillation                                    Lightheadedness
                     disease  \
0        Atrial fibrillation
1  Abdominal aortic aneurysm
2         Separated shoulder
3       Acanthosis nigricans
4        Achilles tendinitis

                                            overview  \
0  In a typical heart rhythm, a tiny cluster of c...
1  An abdominal aortic aneurysm occurs when a low...
2  A separated shoulder is an injury to the ligam...
3  Acanthosis nigricans is a skin condition that ...
4  Achilles tendinitis is an overuse injury of th...

                                           treatment  \
0  Reset the heart rhythm Control the heart rate ...
1  Endovascular repair. This procedure is used mo...
2  Rest. Avoid activities that aggravate your sho...
3  Losing weight. If your acanthosis nigricans is...
4  Exercises. Therapists often prescribe specific...

                                  when_to_see_doctor
0  If you have any signs or symptoms of atrial fi...
1  If you have pain, especially if pain is sudden...
2  Contact your doctor if you have persistent ten...
3  Consult your doctor if you notice changes in y...
4  If you experience persistent pain around the A...
                     disease   doctor_specialty
0        Atrial fibrillation       Cardiologist
1  Abdominal aortic aneurysm  General Physician
2         Separated shoulder  General Physician
3       Acanthosis nigricans  General Physician
4        Achilles tendinitis  General Physician

In [70]:
symptoms_df["symptom"] = symptoms_df["symptom"].astype(str).str.strip()
symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(x.split()))

clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].drop_duplicates().copy()

print("clean_df:", clean_df.shape)
print("عدد الأمراض بعد التنظيف:", clean_df["disease"].nunique())

clean_df: (3148, 3)
عدد الأمراض بعد التنظيف: 597

In [71]:
if "filtered_df" not in globals():
    disease_counts = clean_df["disease"].value_counts()
    top_diseases = disease_counts.head(145).index
    filtered_df = clean_df[clean_df["disease"].isin(top_diseases)].copy()

print("filtered_df:", filtered_df.shape)
print("عدد الأمراض النهائي:", filtered_df["disease"].nunique())

filtered_df: (1401, 3)
عدد الأمراض النهائي: 145

In [72]:
extra_rows = [
    # GERD
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Heartburn"},
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Acid reflux"},
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Burning chest after eating"},

    # Gastritis
    {"disease": "Gastritis", "symptom": "Burning stomach pain"},
    {"disease": "Gastritis", "symptom": "Nausea"},
    {"disease": "Gastritis", "symptom": "Fullness after eating"},

    # Peptic ulcer
    {"disease": "Peptic ulcer", "symptom": "Burning stomach pain"},
    {"disease": "Peptic ulcer", "symptom": "Heartburn"},
    {"disease": "Peptic ulcer", "symptom": "Bloating"},

    # Common cold
    {"disease": "Common cold", "symptom": "Runny nose"},
    {"disease": "Common cold", "symptom": "Sneezing"},
    {"disease": "Common cold", "symptom": "Sore throat"},
    {"disease": "Common cold", "symptom": "Cough"},

    # Flu
    {"disease": "Influenza (flu)", "symptom": "Fever"},
    {"disease": "Influenza (flu)", "symptom": "Cough"},
    {"disease": "Influenza (flu)", "symptom": "Body aches"},
    {"disease": "Influenza (flu)", "symptom": "Fatigue"},

    # UTI
    {"disease": "Urinary tract infection (UTI)", "symptom": "Burning urination"},
    {"disease": "Urinary tract infection (UTI)", "symptom": "Frequent urination"},
    {"disease": "Urinary tract infection (UTI)", "symptom": "Pelvic pain"},

    # Migraine
    {"disease": "Migraine", "symptom": "Headache"},
    {"disease": "Migraine", "symptom": "Nausea"},
    {"disease": "Migraine", "symptom": "Sensitivity to light"},

    # Asthma
    {"disease": "Asthma", "symptom": "Shortness of breath"},
    {"disease": "Asthma", "symptom": "Wheezing"},
    {"disease": "Asthma", "symptom": "Cough"}
]

extra_df = pd.DataFrame(extra_rows)

filtered_df = pd.concat([filtered_df[["disease", "symptom"]], extra_df], ignore_index=True)
filtered_df = filtered_df.drop_duplicates().copy()

print("بعد الإضافة:", filtered_df.shape)
print("عدد الأمراض:", filtered_df["disease"].nunique())

بعد الإضافة: (1424, 2)
عدد الأمراض: 149

In [74]:
embed_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
print("Embedding model loaded")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding model loaded

In [75]:
symptom_texts = filtered_df["symptom"].tolist()
symptom_embeddings = embed_model.encode(symptom_texts)

print("Embeddings shape:", symptom_embeddings.shape)

Embeddings shape: (1424, 384)

In [76]:
arabic_map = {
    # digestive
    "بطني بتولع": "heartburn acid reflux burning chest after eating",
    "بطني بتحرق": "heartburn acid reflux burning chest",
    "حموضة": "heartburn acid reflux",
    "حرقان في المعدة": "heartburn acid reflux burning stomach",
    "حرقة": "heartburn",
    "بعد الاكل": "after eating",
    "بعد الأكل": "after eating",
    "مغص": "abdominal pain",
    "وجع بطن": "abdominal pain",
    "ألم بطن": "abdominal pain",
    "غثيان": "nausea",
    "ترجيع": "vomiting",
    "قيء": "vomiting",
    "نفخة": "bloating",

    # respiratory
    "كحة": "cough",
    "كحه": "cough",
    "سعال": "cough",
    "رشح": "runny nose",
    "عطس": "sneezing",
    "احتقان": "nasal congestion",
    "التهاب الحلق": "sore throat",
    "وجع حلق": "sore throat",
    "ضيق تنفس": "shortness of breath",
    "صفير": "wheezing",

    # fever / general
    "سخونية": "fever",
    "سخونيه": "fever",
    "حرارة": "fever",
    "حراره": "fever",
    "تعب": "fatigue",
    "إرهاق": "fatigue",
    "ارهاق": "fatigue",
    "وجع جسم": "body aches",

    # neuro
    "صداع": "headache",
    "صداع شديد": "headache migraine",
    "دوخة": "dizziness",
    "دوخه": "dizziness",

    # urinary
    "حرقان في البول": "burning urination",
    "كثرة التبول": "frequent urination",
    "كتر التبول": "frequent urination",
}

def normalize_arabic(user_input):
    text = str(user_input).strip().lower()
    extra = []

    for k, v in arabic_map.items():
        if k in text:
            extra.append(v)

    if extra:
        return text + " " + " ".join(extra)

    return text

In [77]:
def predict_disease(user_input, top_k=15):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()
        query_lower = query_text.lower()

        # boosts منطقية
        if "heartburn" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "acid reflux" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "after eating" in query_lower and ("heartburn" in sym_lower or "acid reflux" in sym_lower):
            disease_scores[disease]["score"] += 3

        if "fever" in query_lower and "fever" in sym_lower:
            disease_scores[disease]["score"] += 3
        if "cough" in query_lower and "cough" in sym_lower:
            disease_scores[disease]["score"] += 3

        if "headache" in query_lower and "headache" in sym_lower:
            disease_scores[disease]["score"] += 3

        if "burning urination" in query_lower and "burning urination" in sym_lower:
            disease_scores[disease]["score"] += 4

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    return ranked[:3]

In [78]:
results = predict_disease("بطني بتولع بعد الاكل")

for disease, data in results:
    print("Disease:", disease)
    print("Score:", round(data["score"], 2))
    print("Matched symptoms:", data["matched_symptoms"][:5])
    print("-" * 50)

Disease: Gastroesophageal reflux disease (GERD)
Score: 38.67
Matched symptoms: ['Burning chest after eating', 'Heartburn']
--------------------------------------------------
Disease: Peptic ulcer
Score: 35.5
Matched symptoms: ['Heartburn', 'Burning stomach pain']
--------------------------------------------------
Disease: Stomach cancer
Score: 34.39
Matched symptoms: ['Heartburn', 'Feeling bloated after eating']
--------------------------------------------------

In [79]:
def get_disease_info(disease):
    row = info_df[info_df["disease"] == disease]
    if len(row) == 0:
        return None

    row = row.iloc[0]
    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

In [80]:
def get_doctor(disease):
    row = doctor_df[doctor_df["disease"] == disease]
    if len(row) == 0:
        return "General Physician"

    row = row.iloc[0]

    if "doctor" in doctor_df.columns:
        return row["doctor"]
    elif "doctor_specialty" in doctor_df.columns:
        return row["doctor_specialty"]

    return "General Physician"

In [81]:
def translate_to_ar(text):
    try:
        return GoogleTranslator(source="auto", target="ar").translate(str(text))
    except:
        return str(text)

In [82]:
def chatbot(user_input):
    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض بشكل مبدئي."

    best_disease = predictions[0][0]
    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    # confidence بسيط
    scores = [p[1]["score"] for p in predictions]
    total = sum(scores) if sum(scores) != 0 else 1

    response = "الأمراض المحتملة:\n\n"

    for i, (d, data) in enumerate(predictions, start=1):
        pct = round((data["score"] / total) * 100, 1)
        response += f"{i}️⃣ {translate_to_ar(d)} ({pct}%)\n"

    response += "\n----------------\n\n"
    response += f"التشخيص الأكثر احتمالاً:\n{translate_to_ar(best_disease)}\n\n"

    if info:
        overview = translate_to_ar(info["overview"])
        treatment = translate_to_ar(info["treatment"])
        when = translate_to_ar(info["when"])

        response += f"شرح المرض:\n{overview}\n\n"
        response += f"لتقليل الأعراض:\n{treatment}\n\n"
        response += f"متى يجب زيارة الطبيب؟\n{when}\n\n"

    response += f"التخصص المناسب:\n{translate_to_ar(doctor)}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [83]:
while True:
    user = input("اكتب الأعراض: ")

    if user.lower() == "exit":
        print("تم إنهاء الشات")
        break

    print("\n" + chatbot(user))
    print("\n" + "="*80 + "\n")

اكتب الأعراض:  حموضة بعد الاكل

الأمراض المحتملة:

1️⃣ مرض الجزر المعدي المريئي (GERD) (40.7%)
2️⃣ القرحة الهضمية (33.7%)
3️⃣ سرطان المعدة (25.6%)

----------------

التشخيص الأكثر احتمالاً:
مرض الجزر المعدي المريئي (GERD)

شرح المرض:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث مرض الجزر المعدي المريئي (GERD) عندما يتدفق حمض المعدة بشكل متكرر إلى الأنبوب الذي يربط بين الفم والمعدة (المريء). يمكن أن يؤدي هذا الارتجاع الحمضي إلى تهيج بطانة المريء. يعاني العديد من الأشخاص من الارتجاع الحمضي من وقت لآخر. ارتجاع المريء هو ارتجاع حمض خفيف يحدث مرتين على الأقل في الأسبوع، أو ارتجاع حمض معتدل إلى شديد يحدث مرة واحدة على الأقل في الأسبوع. يمكن لمعظم الناس التحكم في الانزعاج الناتج عن ارتجاع المريء من خلال تغيير نمط الحياة والأدوية المتاحة دون وصفة طبية. لكن بعض الأشخاص المصابين بالارتجاع المعدي المريئي قد يحتاجون إلى أدوية أو جراحة أقوى لتخفيف الأعراض.

لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة. لكن مضادات الحموضة وحدها لن تعالج المريء الملتهب الذي تضرر بسبب حمض المعدة. الإفراط في استخدام بعض مضادات الحموضة يمكن أن يسبب آثارا جانبية، مثل الإسهال أو في بعض الأحيان مشاكل في الكلى. أدوية لتقليل إنتاج الأحماض. تشمل هذه الأدوية — المعروفة باسم حاصرات مستقبلات H-2 — سيميتيدين (تاجاميت إتش بي)، وفاموتيدين (بيبسيد إيه سي)، ونيزاتيدين (أكسيد آر). لا تعمل حاصرات مستقبلات H-2 بنفس سرعة مضادات الحموضة، ولكنها توفر راحة أطول وقد تقلل إنتاج الحمض من المعدة لمدة تصل إلى 12 ساعة. الإصدارات الأقوى متاحة بوصفة طبية. الأدوية التي تمنع إنتاج الحمض وتشفي المريء. هذه الأدوية — المعروفة باسم مثبطات مضخة البروتون — هي حاصرات حمض أقوى من حاصرات مستقبلات H-2 وتتيح وقتًا لشفاء أنسجة المريء التالفة. تشمل مثبطات مضخة البروتون المتاحة دون وصفة طبية لانسوبرازول (بريفاسيد 24 ساعة) وأوميبرازول (بريلوسيك أو تي سي، زيجيريد أو تي سي).

متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية. حدد موعدًا مع طبيبك إذا كنت:
تجربة أعراض ارتجاع المريء الشديدة أو المتكررة
تناول الأدوية المتاحة دون وصفة طبية لعلاج حرقة المعدة أكثر من مرتين في الأسبوع

التخصص المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  بطني بتولع بعد الاكل

الأمراض المحتملة:

1️⃣ مرض الجزر المعدي المريئي (GERD) (35.6%)
2️⃣ القرحة الهضمية (32.7%)
3️⃣ سرطان المعدة (31.7%)

----------------

التشخيص الأكثر احتمالاً:
مرض الجزر المعدي المريئي (GERD)

شرح المرض:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث مرض الجزر المعدي المريئي (GERD) عندما يتدفق حمض المعدة بشكل متكرر إلى الأنبوب الذي يربط بين الفم والمعدة (المريء). يمكن أن يؤدي هذا الارتجاع الحمضي إلى تهيج بطانة المريء. يعاني العديد من الأشخاص من الارتجاع الحمضي من وقت لآخر. ارتجاع المريء هو ارتجاع حمض خفيف يحدث مرتين على الأقل في الأسبوع، أو ارتجاع حمض معتدل إلى شديد يحدث مرة واحدة على الأقل في الأسبوع. يمكن لمعظم الناس التحكم في الانزعاج الناتج عن ارتجاع المريء من خلال تغيير نمط الحياة والأدوية المتاحة دون وصفة طبية. لكن بعض الأشخاص المصابين بالارتجاع المعدي المريئي قد يحتاجون إلى أدوية أو جراحة أقوى لتخفيف الأعراض.

لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة. لكن مضادات الحموضة وحدها لن تعالج المريء الملتهب الذي تضرر بسبب حمض المعدة. الإفراط في استخدام بعض مضادات الحموضة يمكن أن يسبب آثارا جانبية، مثل الإسهال أو في بعض الأحيان مشاكل في الكلى. أدوية لتقليل إنتاج الأحماض. تشمل هذه الأدوية — المعروفة باسم حاصرات مستقبلات H-2 — سيميتيدين (تاجاميت إتش بي)، وفاموتيدين (بيبسيد إيه سي)، ونيزاتيدين (أكسيد آر). لا تعمل حاصرات مستقبلات H-2 بنفس سرعة مضادات الحموضة، ولكنها توفر راحة أطول وقد تقلل إنتاج الحمض من المعدة لمدة تصل إلى 12 ساعة. الإصدارات الأقوى متاحة بوصفة طبية. الأدوية التي تمنع إنتاج الحمض وتشفي المريء. هذه الأدوية — المعروفة باسم مثبطات مضخة البروتون — هي حاصرات حمض أقوى من حاصرات مستقبلات H-2 وتتيح وقتًا لشفاء أنسجة المريء التالفة. تشمل مثبطات مضخة البروتون المتاحة دون وصفة طبية لانسوبرازول (بريفاسيد 24 ساعة) وأوميبرازول (بريلوسيك أو تي سي، زيجيريد أو تي سي).

متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية. حدد موعدًا مع طبيبك إذا كنت:
تجربة أعراض ارتجاع المريء الشديدة أو المتكررة
تناول الأدوية المتاحة دون وصفة طبية لعلاج حرقة المعدة أكثر من مرتين في الأسبوع

التخصص المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  صداع شديد مع غثيان

الأمراض المحتملة:

1️⃣ مرض شاغاس (33.3%)
2️⃣ شلل الأطفال (33.3%)
3️⃣ عدوى الليستيريا (33.3%)

----------------

التشخيص الأكثر احتمالاً:
مرض شاغاس

شرح المرض:
مرض شاغاس (CHAH-gus) هو مرض التهابي ومعدي يسببه طفيل المثقبية الكروزية. تم العثور على هذا الطفيل في براز حشرة الترياتومين (reduviid). يُعرف هذا الخطأ أيضًا باسم "حشرة التقبيل". مرض شاغاس شائع في أمريكا الجنوبية وأمريكا الوسطى والمكسيك، الموطن الرئيسي لحشرة الترياتومين. كما تم العثور على حالات نادرة من مرض شاغاس في جنوب الولايات المتحدة. يُسمى أيضًا داء المثقبيات الأمريكي، ويمكن لمرض شاغاس أن يصيب أي شخص. إذا ترك مرض شاغاس دون علاج، فإنه يمكن أن يسبب لاحقًا مشاكل خطيرة في القلب والجهاز الهضمي. أثناء المرحلة الحادة من العدوى، يركز علاج داء شاغاس على قتل الطفيلي. في الأشخاص الذين يعانون من مرض شاغاس المزمن، لم يعد من الممكن قتل الطفيل. العلاج في هذه المرحلة اللاحقة يدور حول إدارة العلامات والأعراض. يمكنك أيضًا اتخاذ خطوات لمنع العدوى.

لتقليل الأعراض:
المضاعفات المتعلقة بالقلب. قد يشمل العلاج استخدام الأدوية، أو جهاز تنظيم ضربات القلب، أو أجهزة أخرى للتحكم في إيقاع القلب، أو الجراحة، أو حتى زراعة القلب. المضاعفات المتعلقة بالجهاز الهضمي. قد يشمل العلاج تغيير النظام الغذائي، أو تناول الأدوية، أو الكورتيكوستيرويدات، أو الجراحة في الحالات الشديدة.

متى يجب زيارة الطبيب؟
راجع طبيبك إذا كنت تعيش في منطقة ينتشر فيها مرض شاغاس أو سافرت إليها وكانت لديك علامات وأعراض الحالة. قد تشمل الأعراض التورم في موقع الإصابة والحمى والتعب وآلام الجسم والطفح الجلدي والغثيان.

التخصص المناسب:
طبيب عام

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  حرقان في البول وكثرة التبول

الأمراض المحتملة:

1️⃣ عدوى المسالك البولية (UTI) (41.7%)
2️⃣ ضمور المهبل (36.9%)
3️⃣ الأمراض المنقولة جنسيا (الأمراض المنقولة جنسيا) (21.5%)

----------------

التشخيص الأكثر احتمالاً:
عدوى المسالك البولية (UTI)

شرح المرض:
يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. عدوى المسالك البولية (UTI) هي عدوى تصيب أي جزء من جهازك البولي — الكليتين والحالب والمثانة والإحليل. تشمل معظم حالات العدوى الجهاز البولي السفلي — المثانة والإحليل. النساء أكثر عرضة للإصابة بالتهاب المسالك البولية من الرجال. العدوى التي تقتصر على المثانة يمكن أن تكون مؤلمة ومزعجة. ومع ذلك، يمكن أن تحدث عواقب وخيمة إذا انتشر التهاب المسالك البولية إلى الكليتين. عادةً ما يعالج الأطباء التهابات المسالك البولية بالمضادات الحيوية. ولكن يمكنك اتخاذ خطوات لتقليل فرص إصابتك بالتهاب المسالك البولية في المقام الأول.

لتقليل الأعراض:
تريميثوبريم/سلفاميثوكسازول (باكتريم، سيبترا، وأدوية أخرى) فوسفوميسين (مونورول) نيتروفورانتوين (ماكرودانتين، ماكروبيد) سيفالكسين (كيفليكس) سيفترياكسون

متى يجب زيارة الطبيب؟
اتصل بطبيبك إذا كان لديك علامات وأعراض التهاب المسالك البولية.

التخصص المناسب:
مرض معدي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  كحه وسخونيه

الأمراض المحتملة:

1️⃣ ورم ويلمز (33.3%)
2️⃣ حساسية البنسلين (33.3%)
3️⃣ Drug allergy (33.3%)

----------------

التشخيص الأكثر احتمالاً:
ورم ويلمز

شرح المرض:
الجهاز البولي — الذي يشمل الكلى والحالب والمثانة والإحليل — مسؤول عن إزالة الفضلات من الجسم عن طريق البول. ورم ويلمز هو النوع الأكثر شيوعا من سرطان الكلى لدى الأطفال. الجهاز البولي — الذي يشمل الكلى والحالب والمثانة والإحليل — مسؤول عن إزالة الفضلات من الجسم عن طريق البول. ورم ويلمز هو النوع الأكثر شيوعا من سرطان الكلى لدى الأطفال. ورم ويلمز هو سرطان نادر في الكلى يصيب الأطفال في المقام الأول. يُعرف أيضًا باسم الورم الأرومي الكلوي، وهو أكثر أنواع سرطان الكلى شيوعًا لدى الأطفال. غالبًا ما يصيب ورم ويلمز الأطفال الذين تتراوح أعمارهم بين 3 إلى 4 سنوات ويصبح أقل شيوعًا بعد سن 5 سنوات. يحدث ورم ويلمز غالبًا في كلية واحدة فقط، على الرغم من أنه يمكن العثور عليه أحيانًا في كلتا الكليتين في نفس الوقت. على مر السنين، أدى التقدم في تشخيص وعلاج ورم ويلمز إلى تحسن كبير في التوقعات (التشخيص) للأطفال المصابين بهذا المرض. مع العلاج المناسب، تكون التوقعات بالنسبة لمعظم الأطفال المصابين بورم ويلمز جيدة جدًا.

لتقليل الأعراض:
إزالة جزء من الكلية المصابة. يتضمن استئصال الكلية الجزئي إزالة الورم وجزء صغير من أنسجة الكلى المحيطة به. قد يكون استئصال الكلية الجزئي خيارًا إذا كان السرطان صغيرًا جدًا أو إذا كان لدى طفلك كلية واحدة عاملة فقط. إزالة الكلية المصابة والأنسجة المحيطة بها. في استئصال الكلية الجذري، يقوم الأطباء بإزالة الكلية والأنسجة المحيطة بها، بما في ذلك جزء من الحالب وأحيانًا الغدة الكظرية. تتم أيضًا إزالة العقد الليمفاوية القريبة. يمكن للكلية المتبقية أن تزيد من قدرتها وتتولى مهمة تصفية الدم. إزالة كل أو جزء من الكليتين. إذا كان السرطان يؤثر على الكليتين، يقوم الجراح بإزالة أكبر قدر ممكن من السرطان من الكليتين. في عدد قليل من الحالات، قد يعني ذلك إزالة الكليتين، وسيحتاج طفلك بعد ذلك إلى غسيل الكلى. إذا كان زرع الكلى خيارًا، فلن يحتاج طفلك إلى غسيل الكلى.

متى يجب زيارة الطبيب؟
حدد موعدًا مع طبيب طفلك إذا لاحظت أي علامات أو أعراض تثير قلقك. ورم ويلمز نادر، لذلك من المرجح أن يكون هناك شيء آخر يسبب الأعراض، ولكن من المهم التحقق من أي مخاوف.

التخصص المناسب:
طبيب الأورام

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  Exit

تم إنهاء الشات

In [84]:
disease_groups = {
    "digestive": [
        "Gastroesophageal reflux disease (GERD)",
        "Gastritis",
        "Peptic ulcer",
        "Hiatal hernia",
        "Irritable bowel syndrome",
        "Constipation",
        "Diarrhea",
        "Appendicitis",
        "Gallstones",
        "Pancreatitis"
    ],
    "respiratory": [
        "Common cold",
        "Influenza (flu)",
        "Bronchitis",
        "Pneumonia",
        "Asthma",
        "Acute sinusitis",
        "COVID-19"
    ],
    "neurological": [
        "Migraine",
        "Tension headache",
        "Epilepsy"
    ],
    "urinary": [
        "Urinary tract infection (UTI)",
        "Kidney stones"
    ]
}

In [85]:
def detect_context(user_input):
    text = normalize_arabic(user_input).lower()

    if any(x in text for x in ["heartburn", "acid reflux", "after eating", "burning stomach"]):
        return "digestive"

    if any(x in text for x in ["cough", "fever", "runny nose", "sore throat", "wheezing"]):
        return "respiratory"

    if any(x in text for x in ["headache", "migraine", "nausea", "dizziness"]):
        return "neurological"

    if any(x in text for x in ["burning urination", "frequent urination", "pelvic pain"]):
        return "urinary"

    return None

In [86]:
def predict_disease(user_input, top_k=15):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}
    context = detect_context(user_input)

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()
        query_lower = query_text.lower()

        # symptom boosts
        if "heartburn" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "acid reflux" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "fever" in query_lower and "fever" in sym_lower:
            disease_scores[disease]["score"] += 4
        if "cough" in query_lower and "cough" in sym_lower:
            disease_scores[disease]["score"] += 4
        if "headache" in query_lower and "headache" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "nausea" in query_lower and "nausea" in sym_lower:
            disease_scores[disease]["score"] += 4
        if "burning urination" in query_lower and "burning urination" in sym_lower:
            disease_scores[disease]["score"] += 5
        if "frequent urination" in query_lower and "frequent urination" in sym_lower:
            disease_scores[disease]["score"] += 5

        # context boost without deleting any disease
        if context is not None:
            for group_name, diseases in disease_groups.items():
                if disease in diseases and group_name == context:
                    disease_scores[disease]["score"] += 8

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    return ranked[:3]

In [87]:
tests = [
    "حموضة بعد الاكل",
    "بطني بتولع بعد الاكل",
    "صداع شديد مع غثيان",
    "كحه وسخونيه",
    "حرقان في البول وكثرة التبول"
]

for t in tests:
    print("\nINPUT:", t)
    results = predict_disease(t)
    for disease, data in results:
        print("Disease:", disease)
        print("Score:", round(data["score"], 2))
        print("Matched symptoms:", data["matched_symptoms"][:5])
    print("-" * 70)

INPUT: حموضة بعد الاكل
Disease: Gastroesophageal reflux disease (GERD)
Score: 75.92
Matched symptoms: ['Heartburn', 'Burning chest after eating', 'Acid reflux']
Disease: Peptic ulcer
Score: 68.88
Matched symptoms: ['Heartburn', 'Intolerance to fatty foods', 'Appetite changes']
Disease: Stomach cancer
Score: 33.47
Matched symptoms: ['Heartburn', 'Feeling bloated after eating']
----------------------------------------------------------------------

INPUT: بطني بتولع بعد الاكل
Disease: Gastroesophageal reflux disease (GERD)
Score: 51.67
Matched symptoms: ['Burning chest after eating', 'Heartburn']
Disease: Peptic ulcer
Score: 48.5
Matched symptoms: ['Heartburn', 'Burning stomach pain']
Disease: Stomach cancer
Score: 31.39
Matched symptoms: ['Heartburn', 'Feeling bloated after eating']
----------------------------------------------------------------------

INPUT: صداع شديد مع غثيان
Disease: Chagas disease
Score: 34.35
Matched symptoms: ['Headache']
Disease: Polio
Score: 34.35
Matched symptoms: ['Headache']
Disease: Listeria infection
Score: 34.35
Matched symptoms: ['Headache']
----------------------------------------------------------------------

INPUT: كحه وسخونيه
Disease: Acute sinusitis
Score: 39.65
Matched symptoms: ['Fever']
Disease: Wilms' tumor
Score: 31.65
Matched symptoms: ['Fever']
Disease: Penicillin allergy
Score: 31.65
Matched symptoms: ['Fever']
----------------------------------------------------------------------

INPUT: حرقان في البول وكثرة التبول
Disease: Urinary tract infection (UTI)
Score: 65.36
Matched symptoms: ['Burning urination', 'Frequent urination']
Disease: Vaginal atrophy
Score: 43.37
Matched symptoms: ['Frequent urination', 'Burning with urination']
Disease: Neuroendocrine tumors
Score: 24.27
Matched symptoms: ['Frequent urination']
----------------------------------------------------------------------

In [88]:
def get_disease_info(disease):
    row = info_df[info_df["disease"] == disease]

    if len(row) == 0:
        return None

    row = row.iloc[0]

    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

In [89]:
def get_doctor(disease):
    row = doctor_df[doctor_df["disease"] == disease]

    if len(row) == 0:
        return "General Physician"

    if "doctor" in doctor_df.columns:
        return row.iloc[0]["doctor"]

    if "doctor_specialty" in doctor_df.columns:
        return row.iloc[0]["doctor_specialty"]

    return "General Physician"

In [90]:
from deep_translator import GoogleTranslator

def translate_to_ar(text):
    try:
        return GoogleTranslator(source="auto", target="ar").translate(str(text))
    except:
        return str(text)

In [91]:
def chatbot(user_input):
    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض بشكل مبدئي."

    best_disease = predictions[0][0]
    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    scores = [p[1]["score"] for p in predictions]
    total = sum(scores) if sum(scores) != 0 else 1

    response = "الأمراض المحتملة:\n\n"

    for i, (d, data) in enumerate(predictions, start=1):
        pct = round((data["score"] / total) * 100, 1)
        response += f"{i}️⃣ {translate_to_ar(d)} ({pct}%)\n"

    response += "\n----------------\n\n"
    response += f"التشخيص الأكثر احتمالاً:\n{translate_to_ar(best_disease)}\n\n"

    if info:
        response += f"شرح المرض:\n{translate_to_ar(info['overview'])}\n\n"
        response += f"لتقليل الأعراض:\n{translate_to_ar(info['treatment'])}\n\n"
        response += f"متى يجب زيارة الطبيب؟\n{translate_to_ar(info['when'])}\n\n"

    response += f"التخصص المناسب:\n{translate_to_ar(doctor)}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [92]:
while True:
    user = input("اكتب الأعراض: ")

    if user.lower() == "exit":
        print("تم إنهاء الشات")
        break

    print("\n" + chatbot(user))
    print("\n" + "=" * 80 + "\n")

اكتب الأعراض:  حموضة بعد الاكل

الأمراض المحتملة:

1️⃣ مرض الجزر المعدي المريئي (GERD) (42.6%)
2️⃣ القرحة الهضمية (38.6%)
3️⃣ سرطان المعدة (18.8%)

----------------

التشخيص الأكثر احتمالاً:
مرض الجزر المعدي المريئي (GERD)

شرح المرض:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث مرض الجزر المعدي المريئي (GERD) عندما يتدفق حمض المعدة بشكل متكرر إلى الأنبوب الذي يربط بين الفم والمعدة (المريء). يمكن أن يؤدي هذا الارتجاع الحمضي إلى تهيج بطانة المريء. يعاني العديد من الأشخاص من الارتجاع الحمضي من وقت لآخر. ارتجاع المريء هو ارتجاع حمض خفيف يحدث مرتين على الأقل في الأسبوع، أو ارتجاع حمض معتدل إلى شديد يحدث مرة واحدة على الأقل في الأسبوع. يمكن لمعظم الناس التحكم في الانزعاج الناتج عن ارتجاع المريء من خلال تغيير نمط الحياة والأدوية المتاحة دون وصفة طبية. لكن بعض الأشخاص المصابين بالارتجاع المعدي المريئي قد يحتاجون إلى أدوية أو جراحة أقوى لتخفيف الأعراض.

لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة. لكن مضادات الحموضة وحدها لن تعالج المريء الملتهب الذي تضرر بسبب حمض المعدة. الإفراط في استخدام بعض مضادات الحموضة يمكن أن يسبب آثارا جانبية، مثل الإسهال أو في بعض الأحيان مشاكل في الكلى. أدوية لتقليل إنتاج الأحماض. تشمل هذه الأدوية — المعروفة باسم حاصرات مستقبلات H-2 — سيميتيدين (تاجاميت إتش بي)، وفاموتيدين (بيبسيد إيه سي)، ونيزاتيدين (أكسيد آر). لا تعمل حاصرات مستقبلات H-2 بنفس سرعة مضادات الحموضة، ولكنها توفر راحة أطول وقد تقلل إنتاج الحمض من المعدة لمدة تصل إلى 12 ساعة. الإصدارات الأقوى متاحة بوصفة طبية. الأدوية التي تمنع إنتاج الحمض وتشفي المريء. هذه الأدوية — المعروفة باسم مثبطات مضخة البروتون — هي حاصرات حمض أقوى من حاصرات مستقبلات H-2 وتتيح وقتًا لشفاء أنسجة المريء التالفة. تشمل مثبطات مضخة البروتون المتاحة دون وصفة طبية لانسوبرازول (بريفاسيد 24 ساعة) وأوميبرازول (بريلوسيك أو تي سي، زيجيريد أو تي سي).

متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية. حدد موعدًا مع طبيبك إذا كنت:
تجربة أعراض ارتجاع المريء الشديدة أو المتكررة
تناول الأدوية المتاحة دون وصفة طبية لعلاج حرقة المعدة أكثر من مرتين في الأسبوع

التخصص المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  بطني بتولع بعد الاكل

الأمراض المحتملة:

1️⃣ مرض الجزر المعدي المريئي (GERD) (39.3%)
2️⃣ القرحة الهضمية (36.9%)
3️⃣ سرطان المعدة (23.9%)

----------------

التشخيص الأكثر احتمالاً:
مرض الجزر المعدي المريئي (GERD)

شرح المرض:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض. يمكن أن يؤدي الارتجاع المتكرر أو المستمر إلى مرض الجزر المعدي المريئي (GERD). يحدث مرض الجزر المعدي المريئي (GERD) عندما يتدفق حمض المعدة بشكل متكرر إلى الأنبوب الذي يربط بين الفم والمعدة (المريء). يمكن أن يؤدي هذا الارتجاع الحمضي إلى تهيج بطانة المريء. يعاني العديد من الأشخاص من الارتجاع الحمضي من وقت لآخر. ارتجاع المريء هو ارتجاع حمض خفيف يحدث مرتين على الأقل في الأسبوع، أو ارتجاع حمض معتدل إلى شديد يحدث مرة واحدة على الأقل في الأسبوع. يمكن لمعظم الناس التحكم في الانزعاج الناتج عن ارتجاع المريء من خلال تغيير نمط الحياة والأدوية المتاحة دون وصفة طبية. لكن بعض الأشخاص المصابين بالارتجاع المعدي المريئي قد يحتاجون إلى أدوية أو جراحة أقوى لتخفيف الأعراض.

لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة. لكن مضادات الحموضة وحدها لن تعالج المريء الملتهب الذي تضرر بسبب حمض المعدة. الإفراط في استخدام بعض مضادات الحموضة يمكن أن يسبب آثارا جانبية، مثل الإسهال أو في بعض الأحيان مشاكل في الكلى. أدوية لتقليل إنتاج الأحماض. تشمل هذه الأدوية — المعروفة باسم حاصرات مستقبلات H-2 — سيميتيدين (تاجاميت إتش بي)، وفاموتيدين (بيبسيد إيه سي)، ونيزاتيدين (أكسيد آر). لا تعمل حاصرات مستقبلات H-2 بنفس سرعة مضادات الحموضة، ولكنها توفر راحة أطول وقد تقلل إنتاج الحمض من المعدة لمدة تصل إلى 12 ساعة. الإصدارات الأقوى متاحة بوصفة طبية. الأدوية التي تمنع إنتاج الحمض وتشفي المريء. هذه الأدوية — المعروفة باسم مثبطات مضخة البروتون — هي حاصرات حمض أقوى من حاصرات مستقبلات H-2 وتتيح وقتًا لشفاء أنسجة المريء التالفة. تشمل مثبطات مضخة البروتون المتاحة دون وصفة طبية لانسوبرازول (بريفاسيد 24 ساعة) وأوميبرازول (بريلوسيك أو تي سي، زيجيريد أو تي سي).

متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية. حدد موعدًا مع طبيبك إذا كنت:
تجربة أعراض ارتجاع المريء الشديدة أو المتكررة
تناول الأدوية المتاحة دون وصفة طبية لعلاج حرقة المعدة أكثر من مرتين في الأسبوع

التخصص المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  صداع شديد مع غثيان

الأمراض المحتملة:

1️⃣ مرض شاغاس (33.3%)
2️⃣ شلل الأطفال (33.3%)
3️⃣ عدوى الليستيريا (33.3%)

----------------

التشخيص الأكثر احتمالاً:
مرض شاغاس

شرح المرض:
مرض شاغاس (CHAH-gus) هو مرض التهابي ومعدي يسببه طفيل المثقبية الكروزية. تم العثور على هذا الطفيل في براز حشرة الترياتومين (reduviid). يُعرف هذا الخطأ أيضًا باسم "حشرة التقبيل". مرض شاغاس شائع في أمريكا الجنوبية وأمريكا الوسطى والمكسيك، الموطن الرئيسي لحشرة الترياتومين. كما تم العثور على حالات نادرة من مرض شاغاس في جنوب الولايات المتحدة. يُسمى أيضًا داء المثقبيات الأمريكي، ويمكن لمرض شاغاس أن يصيب أي شخص. إذا ترك مرض شاغاس دون علاج، فإنه يمكن أن يسبب لاحقًا مشاكل خطيرة في القلب والجهاز الهضمي. أثناء المرحلة الحادة من العدوى، يركز علاج داء شاغاس على قتل الطفيلي. في الأشخاص الذين يعانون من مرض شاغاس المزمن، لم يعد من الممكن قتل الطفيل. العلاج في هذه المرحلة اللاحقة يدور حول إدارة العلامات والأعراض. يمكنك أيضًا اتخاذ خطوات لمنع العدوى.

لتقليل الأعراض:
المضاعفات المتعلقة بالقلب. قد يشمل العلاج استخدام الأدوية، أو جهاز تنظيم ضربات القلب، أو أجهزة أخرى للتحكم في إيقاع القلب، أو الجراحة، أو حتى زراعة القلب. المضاعفات المتعلقة بالجهاز الهضمي. قد يشمل العلاج تغيير النظام الغذائي، أو تناول الأدوية، أو الكورتيكوستيرويدات، أو الجراحة في الحالات الشديدة.

متى يجب زيارة الطبيب؟
راجع طبيبك إذا كنت تعيش في منطقة ينتشر فيها مرض شاغاس أو سافرت إليها وكانت لديك علامات وأعراض الحالة. قد تشمل الأعراض التورم في موقع الإصابة والحمى والتعب وآلام الجسم والطفح الجلدي والغثيان.

التخصص المناسب:
طبيب عام

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  كحه وسخونيه

الأمراض المحتملة:

1️⃣ التهاب الجيوب الأنفية الحاد (38.5%)
2️⃣ ورم ويلمز (30.7%)
3️⃣ حساسية البنسلين (30.7%)

----------------

التشخيص الأكثر احتمالاً:
التهاب الجيوب الأنفية الحاد

شرح المرض:
يؤدي التهاب الجيوب الأنفية الحاد إلى التهاب وتورم المساحات داخل أنفك (الجيوب الأنفية). وهذا يتداخل مع التصريف ويسبب تراكم المخاط. في حالة التهاب الجيوب الأنفية الحاد، قد يكون من الصعب التنفس من خلال أنفك. قد تشعر بأن المنطقة المحيطة بعينيك ووجهك منتفخة، وقد تشعر بألم نابض في الوجه أو صداع. يحدث التهاب الجيوب الأنفية الحاد في الغالب بسبب نزلات البرد. ما لم تتطور عدوى بكتيرية، فإن معظم الحالات تشفى خلال أسبوع إلى 10 أيام. قد تكون العلاجات المنزلية هي كل ما تحتاجه لعلاج التهاب الجيوب الأنفية الحاد. يسمى التهاب الجيوب الأنفية الذي يستمر لأكثر من 12 أسبوعًا على الرغم من العلاج الطبي بالتهاب الجيوب الأنفية المزمن.

لتقليل الأعراض:
رذاذ الأنف الملحي، والذي تقوم برشه في أنفك عدة مرات يوميًا لشطف الممرات الأنفية. الكورتيكوستيرويدات الأنفية. تساعد بخاخات الأنف هذه على منع الالتهاب وعلاجه. تشمل الأمثلة فلوتيكاسون (Flonase Allergy Relief، وFlonase Sensimist Allergy Relief، وغيرهما)، وبوديزونيد (Rhinocort Allergy)، وموميتازون (Nasonex)، وبيكلوميثازون (Beconase AQ، وQnasl، وغيرهما). مزيلات الاحتقان. تتوفر هذه الأدوية في صورة سوائل وأقراص وبخاخات أنفية لا تستلزم وصفة طبية، أو في صورة سوائل موصوفة طبيًا أو بدون وصفة طبية. استخدم مزيلات احتقان الأنف لبضعة أيام فقط. وإلا فإنها قد تتسبب في عودة الازدحام الشديد (الازدحام المرتد). أدوية الحساسية. إذا كان التهاب الجيوب الأنفية لديك بسبب الحساسية، فإن استخدام أدوية الحساسية قد يساعد في تقليل أعراض الحساسية. مسكنات الألم المتاحة دون وصفة طبية، مثل أسيتامينوفين (تيلينول، وغيره)، أو إيبوبروفين (أدفيل، وموترين آي بي، وغيرهما) أو الأسبرين.
توخي الحذر عند إعطاء الأسبرين للأطفال أو المراهقين. على الرغم من الموافقة على استخدام الأسبرين للأطفال الأكبر من 3 سنوات، إلا أن الأطفال والمراهقين الذين يتعافون من جدري الماء أو الأعراض الشبيهة بالأنفلونزا يجب ألا يتناولوا الأسبرين أبدًا. وذلك لأن الأسبرين مرتبط بمتلازمة راي، وهي حالة نادرة ولكنها قد تهدد الحياة لدى هؤلاء الأطفال.

متى يجب زيارة الطبيب؟
لا يحتاج معظم الأشخاص المصابين بالتهاب الجيوب الأنفية الحاد إلى زيارة الطبيب. اتصل بطبيبك إذا كان لديك أي مما يلي:
استمرار الأعراض لأكثر من أسبوع أو نحو ذلك
الأعراض التي تتفاقم بعد أن يبدو أنها تتحسن
حمى مستمرة
تاريخ من التهاب الجيوب الأنفية المتكرر أو المزمن
 قم بزيارة الطبيب على الفور إذا كان لديك علامات أو أعراض قد تشير إلى وجود عدوى خطيرة:
ألم أو تورم أو احمرار حول عينيك
ارتفاع في درجة الحرارة
ارتباك
الرؤية المزدوجة أو تغيرات الرؤية الأخرى
تصلب الرقبة

التخصص المناسب:
طبيب عام

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  حرقان في البول وكثرة التبول

الأمراض المحتملة:

1️⃣ عدوى المسالك البولية (UTI) (49.1%)
2️⃣ ضمور المهبل (32.6%)
3️⃣ أورام الغدد الصم العصبية (18.2%)

----------------

التشخيص الأكثر احتمالاً:
عدوى المسالك البولية (UTI)

شرح المرض:
يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. يقوم جهازك البولي — الذي يشمل الكليتين والحالب والمثانة والإحليل — بإزالة الفضلات من الجسم عن طريق البول. تنتج الكليتان، الموجودتان في الجزء الخلفي من الجزء العلوي من البطن، البول عن طريق تصفية الفضلات والسوائل من الدم. عدوى المسالك البولية (UTI) هي عدوى تصيب أي جزء من جهازك البولي — الكليتين والحالب والمثانة والإحليل. تشمل معظم حالات العدوى الجهاز البولي السفلي — المثانة والإحليل. النساء أكثر عرضة للإصابة بالتهاب المسالك البولية من الرجال. العدوى التي تقتصر على المثانة يمكن أن تكون مؤلمة ومزعجة. ومع ذلك، يمكن أن تحدث عواقب وخيمة إذا انتشر التهاب المسالك البولية إلى الكليتين. عادةً ما يعالج الأطباء التهابات المسالك البولية بالمضادات الحيوية. ولكن يمكنك اتخاذ خطوات لتقليل فرص إصابتك بالتهاب المسالك البولية في المقام الأول.

لتقليل الأعراض:
تريميثوبريم/سلفاميثوكسازول (باكتريم، سيبترا، وأدوية أخرى) فوسفوميسين (مونورول) نيتروفورانتوين (ماكرودانتين، ماكروبيد) سيفالكسين (كيفليكس) سيفترياكسون

متى يجب زيارة الطبيب؟
اتصل بطبيبك إذا كان لديك علامات وأعراض التهاب المسالك البولية.

التخصص المناسب:
مرض معدي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

================================================================================

اكتب الأعراض:  exit

تم إنهاء الشات

In [93]:
print("عدد الأمراض في filtered_df:", filtered_df["disease"].nunique())

if "production_df" in globals():
    print("عدد الأمراض في production_df:", production_df["disease"].nunique())

عدد الأمراض في filtered_df: 149

In [95]:
current_diseases = sorted(filtered_df["disease"].unique())

print("عدد الأمراض:", len(current_diseases))

for d in current_diseases:
    print(d)

عدد الأمراض: 149
Acute kidney failure
Acute sinusitis
Adult attention-deficit/hyperactivity disorder (ADHD)
Allergies
Anemia
Angelman syndrome
Anorexia nervosa
Antisocial personality disorder
Anxiety disorders
Asthma
Blastocystis hominis
Body dysmorphic disorder
Brain aneurysm
Brain tumor
Brucellosis
Cancer
Carbon monoxide poisoning
Cardiogenic shock
Celiac disease
Cellulitis
Chagas disease
Chemo brain
Chronic kidney disease
Chronic sinusitis
Cirrhosis
Common cold
Concussion
Coronavirus disease 2019 (COVID-19)
Cryptosporidium infection
Cyclospora infection
Cyclothymia (cyclothymic disorder)
Dengue fever
Diabetes
Diabetes insipidus
Diabetic coma
Diabetic hyperosmolar syndrome
Diabetic hypoglycemia
Diabetic ketoacidosis
Diabetic nephropathy
Down syndrome
Drug allergy
Dumping syndrome
Dust mite allergy
Dysphagia
Ear infection (middle ear)
Ehrlichiosis and anaplasmosis
Eisenmenger syndrome
Encephalitis
End-stage renal disease
Fetal alcohol syndrome
Fibromuscular dysplasia
Gangrene
Gastritis
Gastroesophageal reflux disease (GERD)
Gastroparesis
Glioma
Granulomatosis with polyangiitis
Graves' disease
H1N1 flu (swine flu)
HIV/AIDS
Hantavirus pulmonary syndrome
Hashimoto's disease
Heart arrhythmia
Heart murmurs
Heat exhaustion
Hemochromatosis
Hepatitis A
Hepatitis B
Histoplasmosis
Hunter syndrome
Hyperparathyroidism
Hyperthyroidism (overactive thyroid)
Hyponatremia
Hypoplastic left heart syndrome
Hypothermia
Hypothyroidism (underactive thyroid)
Infertility
Influenza (flu)
Intermittent explosive disorder
Jellyfish stings
Leukemia
Listeria infection
Liver disease
Lupus
Malaria
Membranous nephropathy
Meningitis
Mental illness
Mesothelioma
Migraine
Mitral valve stenosis
Multiple myeloma
Multisystem inflammatory syndrome in children (MIS-C) and COVID-19
Muscular dystrophy
Nasal and paranasal tumors
Nasal polyps
Neuroblastoma
Neuroendocrine tumors
Norovirus infection
Occupational asthma
Ovarian cancer
Paget's disease of the breast
Pancreatitis
Panic attacks and panic disorder
Pediatric obstructive sleep apnea
Penicillin allergy
Peptic ulcer
Peripheral neuropathy
Peritonitis
Persistent depressive disorder (dysthymia)
Persistent post-concussive symptoms (Post-concussion syndrome)
Pet allergy
Polio
Porphyria
Postpartum depression
Prescription drug abuse
Primary ovarian insufficiency
Primary sclerosing cholangitis
Progressive supranuclear palsy
Prolactinoma
Rabies
Rheumatoid arthritis
Scorpion sting
Serotonin syndrome
Sexually transmitted diseases (STDs)
Shingles
Sick sinus syndrome
Sleep apnea
Small intestinal bacterial overgrowth (SIBO)
Snoring
Soft palate cancer
Sore throat
Spinal headaches
Stomach cancer
Sudden cardiac arrest
Supraventricular tachycardia
Tonsillitis
Toxic hepatitis
Tuberculosis
Type 2 diabetes
Typhoid fever
Ulcerative colitis
Urinary tract infection (UTI)
Vaginal atrophy
Valley fever
Vesicoureteral reflux
Vocal cord paralysis
Waldenstrom macroglobulinemia
Wilms' tumor

In [96]:
diseases_list_df = pd.DataFrame({"disease": current_diseases})
diseases_list_df.to_csv("current_diseases_list.csv", index=False)

print("تم حفظ القائمة في current_diseases_list.csv")

تم حفظ القائمة في current_diseases_list.csv

In [97]:
print("Gastroesophageal reflux disease (GERD)" in current_diseases)

True

In [98]:
print("Migraine" in current_diseases)

True

In [99]:
print("Influenza (flu)" in current_diseases)

True

In [100]:
check_diseases = [
    "Gastroesophageal reflux disease (GERD)",
    "Gastritis",
    "Peptic ulcer",
    "Hiatal hernia",
    "Migraine",
    "Influenza (flu)",
    "Common cold",
    "Bronchitis",
    "Pneumonia",
    "Urinary tract infection (UTI)"
]

for d in check_diseases:
    print(d, "->", d in current_diseases)

Gastroesophageal reflux disease (GERD) -> True
Gastritis -> True
Peptic ulcer -> True
Hiatal hernia -> False
Migraine -> True
Influenza (flu) -> True
Common cold -> True
Bronchitis -> False
Pneumonia -> False
Urinary tract infection (UTI) -> True

In [101]:
test_cases = [
    ("حموضة بعد الاكل", "Gastroesophageal reflux disease (GERD)"),
    ("بطني بتولع بعد الاكل", "Gastroesophageal reflux disease (GERD)"),
    ("ألم وحرقان في المعدة", "Gastritis"),
    ("وجع معدة وحرقان", "Peptic ulcer"),
    ("صداع شديد مع غثيان", "Migraine"),
    ("كحه وسخونيه", "Influenza (flu)"),
    ("رشح وكحه والتهاب حلق", "Common cold"),
    ("حرقان في البول وكثرة التبول", "Urinary tract infection (UTI)"),
    ("عندي ضيق تنفس وصفير", "Asthma"),
    ("عطس ورشح وحكة", "Allergies")
]

In [102]:
def test_chatbot():
    for text, expected in test_cases:
        results = predict_disease(text)

        predicted = results[0][0] if len(results) > 0 else "None"

        print("=" * 80)
        print("Input:", text)
        print("Expected:", expected)
        print("Predicted:", predicted)

        print("Top 3:")
        for disease, data in results:
            print("-", disease, round(data["score"], 2))

In [103]:
test_chatbot()

================================================================================
Input: حموضة بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 75.92
- Peptic ulcer 68.88
- Stomach cancer 33.47
================================================================================
Input: بطني بتولع بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 51.67
- Peptic ulcer 48.5
- Stomach cancer 31.39
================================================================================
Input: ألم وحرقان في المعدة
Expected: Gastritis
Predicted: Peptic ulcer
Top 3:
- Peptic ulcer 59.5
- Stomach cancer 40.56
- Gastroesophageal reflux disease (GERD) 29.96
================================================================================
Input: وجع معدة وحرقان
Expected: Peptic ulcer
Predicted: Gastritis
Top 3:
- Gastritis 12.8
- Peptic ulcer 12.8
- Jellyfish stings 12.78
================================================================================
Input: صداع شديد مع غثيان
Expected: Migraine
Predicted: Chagas disease
Top 3:
- Chagas disease 34.35
- Polio 34.35
- Listeria infection 34.35
================================================================================
Input: كحه وسخونيه
Expected: Influenza (flu)
Predicted: Acute sinusitis
Top 3:
- Acute sinusitis 39.65
- Wilms' tumor 31.65
- Penicillin allergy 31.65
================================================================================
Input: رشح وكحه والتهاب حلق
Expected: Common cold
Predicted: Common cold
Top 3:
- Common cold 56.12
- Coronavirus disease 2019 (COVID-19) 40.12
- Asthma 30.24
================================================================================
Input: حرقان في البول وكثرة التبول
Expected: Urinary tract infection (UTI)
Predicted: Urinary tract infection (UTI)
Top 3:
- Urinary tract infection (UTI) 65.36
- Vaginal atrophy 43.37
- Neuroendocrine tumors 24.27
================================================================================
Input: عندي ضيق تنفس وصفير
Expected: Asthma
Predicted: Acute sinusitis
Top 3:
- Acute sinusitis 31.42
- Cardiogenic shock 23.91
- Granulomatosis with polyangiitis 23.63
================================================================================
Input: عطس ورشح وحكة
Expected: Allergies
Predicted: Dust mite allergy
Top 3:
- Dust mite allergy 40.22
- Pet allergy 40.22
- Common cold 29.86

In [111]:
def predict_disease(user_input, top_k=15):

    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}
    context = detect_context(user_input)

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]

        
        score = float(similarities[i])

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()
        query_lower = query_text.lower()

        # ===== BOOSTS =====
        if "headache" in sym_lower and "headache" in query_lower:
            disease_scores[disease]["score"] += 5

        if "nausea" in sym_lower and "nausea" in query_lower:
            disease_scores[disease]["score"] += 4

        if "cough" in sym_lower and "cough" in query_lower:
            disease_scores[disease]["score"] += 4

        if "fever" in sym_lower and "fever" in query_lower:
            disease_scores[disease]["score"] += 4

        # 🔥 SUPER BOOSTS
        if disease == "Migraine" and ("headache" in query_lower and "nausea" in query_lower):
            disease_scores[disease]["score"] += 20

        if disease in ["Influenza (flu)", "Common cold", "Bronchitis", "COVID-19"]:
            if "cough" in query_lower and "fever" in query_lower:
                disease_scores[disease]["score"] += 15

        if disease == "Asthma":
            if "shortness of breath" in query_lower or "wheezing" in query_lower:
                disease_scores[disease]["score"] += 15

        # 🔥 PENALTY (مكانها الصح)
        rare_diseases = [
            "Chagas disease", "Polio", "Listeria infection",
            "Wilms' tumor", "Neuroendocrine tumors",
            "Granulomatosis with polyangiitis",
            "Cardiogenic shock"
        ]

        if disease in rare_diseases:
            disease_scores[disease]["score"] -= 10

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    return ranked[:3]

In [112]:
test_chatbot()

================================================================================
Input: حموضة بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 41.92
- Peptic ulcer 39.88
- Stomach cancer 28.47
================================================================================
Input: بطني بتولع بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 30.67
- Peptic ulcer 27.5
- Stomach cancer 26.39
================================================================================
Input: ألم وحرقان في المعدة
Expected: Gastritis
Predicted: Peptic ulcer
Top 3:
- Peptic ulcer 38.5
- Stomach cancer 35.56
- Gastritis 21.55
================================================================================
Input: وجع معدة وحرقان
Expected: Peptic ulcer
Predicted: Gastritis
Top 3:
- Gastritis 12.8
- Peptic ulcer 12.8
- Jellyfish stings 12.78
================================================================================
Input: صداع شديد مع غثيان
Expected: Migraine
Predicted: Dengue fever
Top 3:
- Dengue fever 34.35
- Valley fever 34.35
- Waldenstrom macroglobulinemia 34.35
================================================================================
Input: كحه وسخونيه
Expected: Influenza (flu)
Predicted: Penicillin allergy
Top 3:
- Penicillin allergy 31.65
- Drug allergy 31.65
- Toxic hepatitis 31.65
================================================================================
Input: رشح وكحه والتهاب حلق
Expected: Common cold
Predicted: Coronavirus disease 2019 (COVID-19)
Top 3:
- Coronavirus disease 2019 (COVID-19) 40.12
- Common cold 40.12
- Asthma 22.24
================================================================================
Input: حرقان في البول وكثرة التبول
Expected: Urinary tract infection (UTI)
Predicted: Urinary tract infection (UTI)
Top 3:
- Urinary tract infection (UTI) 39.36
- Vaginal atrophy 38.37
- Diabetic coma 19.27
================================================================================
Input: عندي ضيق تنفس وصفير
Expected: Asthma
Predicted: Soft palate cancer
Top 3:
- Soft palate cancer 23.42
- Acute sinusitis 23.42
- Chronic sinusitis 23.42
================================================================================
Input: عطس ورشح وحكة
Expected: Allergies
Predicted: Dust mite allergy
Top 3:
- Dust mite allergy 40.22
- Pet allergy 40.22
- Allergies 21.86

In [113]:
disease_alias = {
    "Dust mite allergy": "Allergies",
    "Pet allergy": "Allergies",
    "Penicillin allergy": "Drug allergy",
    "H1N1 flu (swine flu)": "Influenza (flu)",
    "Coronavirus disease 2019 (COVID-19)": "Common cold"
}

In [114]:
def predict_disease(user_input, top_k=20):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}
    query_lower = query_text.lower()

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        # alias mapping
        disease = disease_alias.get(disease, disease)

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()

        # generic symptom boosts
        if "heartburn" in sym_lower and "heartburn" in query_lower:
            disease_scores[disease]["score"] += 8
        if "acid reflux" in sym_lower and "acid reflux" in query_lower:
            disease_scores[disease]["score"] += 8
        if "cough" in sym_lower and "cough" in query_lower:
            disease_scores[disease]["score"] += 6
        if "fever" in sym_lower and "fever" in query_lower:
            disease_scores[disease]["score"] += 6
        if "headache" in sym_lower and "headache" in query_lower:
            disease_scores[disease]["score"] += 8
        if "nausea" in sym_lower and "nausea" in query_lower:
            disease_scores[disease]["score"] += 6
        if "shortness of breath" in sym_lower and "shortness of breath" in query_lower:
            disease_scores[disease]["score"] += 8
        if "wheezing" in sym_lower and "wheezing" in query_lower:
            disease_scores[disease]["score"] += 8
        if "burning urination" in sym_lower and "burning urination" in query_lower:
            disease_scores[disease]["score"] += 8
        if "frequent urination" in sym_lower and "frequent urination" in query_lower:
            disease_scores[disease]["score"] += 8

        # digestive anchors
        if disease == "Gastroesophageal reflux disease (GERD)" and (
            "heartburn" in query_lower or "acid reflux" in query_lower or "after eating" in query_lower
        ):
            disease_scores[disease]["score"] += 20

        if disease == "Gastritis" and (
            "burning stomach" in query_lower or "stomach pain" in query_lower or "nausea" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Peptic ulcer" and (
            "burning" in query_lower or "stomach pain" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        # neuro anchors
        if disease == "Migraine" and ("headache" in query_lower and "nausea" in query_lower):
            disease_scores[disease]["score"] += 30

        # respiratory anchors
        if disease == "Influenza (flu)" and ("cough" in query_lower and "fever" in query_lower):
            disease_scores[disease]["score"] += 25

        if disease == "Common cold" and (
            "runny nose" in query_lower or "sore throat" in query_lower or "cough" in query_lower
        ):
            disease_scores[disease]["score"] += 18

        if disease == "Asthma" and (
            "shortness of breath" in query_lower or "wheezing" in query_lower
        ):
            disease_scores[disease]["score"] += 25

        # urinary anchor
        if disease == "Urinary tract infection (UTI)" and (
            "burning urination" in query_lower and "frequent urination" in query_lower
        ):
            disease_scores[disease]["score"] += 25

        # penalties: clearly bad candidates
        if disease in [
            "Stomach cancer", "Soft palate cancer", "Wilms' tumor",
            "Waldenstrom macroglobulinemia", "Valley fever",
            "Toxic hepatitis", "Drug allergy", "Penicillin allergy",
            "Dengue fever", "Diabetic coma", "Jellyfish stings"
        ]:
            disease_scores[disease]["score"] -= 15

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    return ranked[:3]

In [115]:
arabic_map.update({
    "ألم وحرقان في المعدة": "burning stomach pain nausea gastritis",
    "وجع معدة وحرقان": "stomach pain burning peptic ulcer gastritis",
    "صداع شديد": "severe headache migraine",
    "صداع شديد مع غثيان": "severe headache nausea migraine",
    "كحه وسخونيه": "cough fever flu",
    "كحة وسخونية": "cough fever flu",
    "رشح وكحه والتهاب حلق": "runny nose cough sore throat common cold",
    "ضيق تنفس": "shortness of breath",
    "صفير": "wheezing asthma",
    "عندي ضيق تنفس وصفير": "shortness of breath wheezing asthma",
    "عطس ورشح وحكة": "sneezing runny nose itching allergy"
})

In [116]:
test_chatbot()

================================================================================
Input: حموضة بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 117.92
- Peptic ulcer 47.88
- Gastroparesis 32.91
================================================================================
Input: بطني بتولع بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 78.67
- Peptic ulcer 59.5
- Dysphagia 22.45
================================================================================
Input: ألم وحرقان في المعدة
Expected: Gastritis
Predicted: Gastritis
Top 3:
- Gastritis 32.12
- Peptic ulcer 32.12
- Typhoid fever 18.84
================================================================================
Input: وجع معدة وحرقان
Expected: Peptic ulcer
Predicted: Peptic ulcer
Top 3:
- Peptic ulcer 31.93
- Gastritis 31.93
- Typhoid fever 19.46
================================================================================
Input: صداع شديد مع غثيان
Expected: Migraine
Predicted: Chronic sinusitis
Top 3:
- Chronic sinusitis 31.42
- Common cold 31.42
- Glioma 31.42
================================================================================
Input: كحه وسخونيه
Expected: Influenza (flu)
Predicted: Influenza (flu)
Top 3:
- Influenza (flu) 54.16
- Common cold 47.16
- Chagas disease 29.16
================================================================================
Input: رشح وكحه والتهاب حلق
Expected: Common cold
Predicted: Common cold
Top 3:
- Common cold 117.61
- Influenza (flu) 63.61
- Allergies 46.96
================================================================================
Input: حرقان في البول وكثرة التبول
Expected: Urinary tract infection (UTI)
Predicted: Urinary tract infection (UTI)
Top 3:
- Urinary tract infection (UTI) 105.36
- Vaginal atrophy 62.39
- Vesicoureteral reflux 34.29
================================================================================
Input: عندي ضيق تنفس وصفير
Expected: Asthma
Predicted: Granulomatosis with polyangiitis
Top 3:
- Granulomatosis with polyangiitis 37.77
- Anemia 28.82
- Influenza (flu) 28.82
================================================================================
Input: عطس ورشح وحكة
Expected: Allergies
Predicted: Allergies
Top 3:
- Allergies 126.79
- Common cold 107.77
- Sore throat 37.07

In [117]:
arabic_map.update({
    "صداع شديد مع غثيان": "migraine severe headache nausea sensitivity to light",
    "صداع شديد": "migraine severe headache",
    "صداع": "headache migraine",
    "غثيان": "nausea",
    "صداع نصفي": "migraine headache nausea",

    "عندي ضيق تنفس وصفير": "asthma shortness of breath wheezing",
    "ضيق تنفس وصفير": "asthma shortness of breath wheezing",
    "ضيق تنفس": "shortness of breath asthma",
    "صفير": "wheezing asthma"
})

In [121]:
def predict_disease(user_input, top_k=20):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}
    query_lower = query_text.lower()

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        disease = disease_alias.get(disease, disease)

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()

        if "heartburn" in sym_lower and "heartburn" in query_lower:
            disease_scores[disease]["score"] += 8
        if "acid reflux" in sym_lower and "acid reflux" in query_lower:
            disease_scores[disease]["score"] += 8
        if "cough" in sym_lower and "cough" in query_lower:
            disease_scores[disease]["score"] += 6
        if "fever" in sym_lower and "fever" in query_lower:
            disease_scores[disease]["score"] += 6
        if "headache" in sym_lower and "headache" in query_lower:
            disease_scores[disease]["score"] += 8
        if "nausea" in sym_lower and "nausea" in query_lower:
            disease_scores[disease]["score"] += 6
        if "shortness of breath" in sym_lower and "shortness of breath" in query_lower:
            disease_scores[disease]["score"] += 8
        if "wheezing" in sym_lower and "wheezing" in query_lower:
            disease_scores[disease]["score"] += 8
        if "burning urination" in sym_lower and "burning urination" in query_lower:
            disease_scores[disease]["score"] += 8
        if "frequent urination" in sym_lower and "frequent urination" in query_lower:
            disease_scores[disease]["score"] += 8

        if disease == "Gastroesophageal reflux disease (GERD)" and (
            "heartburn" in query_lower or "acid reflux" in query_lower or "after eating" in query_lower
        ):
            disease_scores[disease]["score"] += 20

        if disease == "Gastritis" and (
            "burning stomach" in query_lower or "stomach pain" in query_lower or "nausea" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Peptic ulcer" and (
            "burning" in query_lower or "stomach pain" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Migraine":
            if "headache" in query_lower:
                disease_scores[disease]["score"] += 15
            if "nausea" in query_lower:
                disease_scores[disease]["score"] += 10
            if "migraine" in query_lower:
                disease_scores[disease]["score"] += 20
            if "headache" in query_lower and "nausea" in query_lower:
                disease_scores[disease]["score"] += 25

        if disease in ["Influenza (flu)", "Common cold", "Bronchitis", "COVID-19"]:
            if "cough" in query_lower and "fever" in query_lower:
                disease_scores[disease]["score"] += 15

        if disease == "Asthma":
            if "shortness of breath" in query_lower:
                disease_scores[disease]["score"] += 18
            if "wheezing" in query_lower:
                disease_scores[disease]["score"] += 18
            if "asthma" in query_lower:
                disease_scores[disease]["score"] += 15
            if "shortness of breath" in query_lower and "wheezing" in query_lower:
                disease_scores[disease]["score"] += 25

        if disease == "Urinary tract infection (UTI)" and (
            "burning urination" in query_lower and "frequent urination" in query_lower
        ):
            disease_scores[disease]["score"] += 25

        if disease in [
            "Stomach cancer", "Soft palate cancer", "Wilms' tumor",
            "Waldenstrom macroglobulinemia", "Valley fever",
            "Toxic hepatitis", "Drug allergy", "Penicillin allergy",
            "Dengue fever", "Diabetic coma", "Jellyfish stings",
            "Chagas disease", "Polio", "Listeria infection",
            "Granulomatosis with polyangiitis", "Glioma"
        ]:
            disease_scores[disease]["score"] -= 20

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )
    
    

    return ranked[:3]

SyntaxError: 'return' outside function (1908952261.py, line 113)

================================================================================
Input: حموضة بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 117.92
- Peptic ulcer 47.88
- Gastroparesis 32.91
================================================================================
Input: بطني بتولع بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 78.67
- Peptic ulcer 59.5
- Dysphagia 22.45
================================================================================
Input: ألم وحرقان في المعدة
Expected: Gastritis
Predicted: Gastritis
Top 3:
- Gastritis 32.12
- Peptic ulcer 32.12
- Typhoid fever 18.84
================================================================================
Input: وجع معدة وحرقان
Expected: Peptic ulcer
Predicted: Peptic ulcer
Top 3:
- Peptic ulcer 31.93
- Gastritis 31.93
- Typhoid fever 19.46
================================================================================
Input: صداع شديد مع غثيان
Expected: Migraine
Predicted: Influenza (flu)
Top 3:
- Influenza (flu) 57.36
- Typhoid fever 28.68
- Common cold 28.68
================================================================================
Input: كحه وسخونيه
Expected: Influenza (flu)
Predicted: Influenza (flu)
Top 3:
- Influenza (flu) 44.16
- Common cold 44.16
- Primary sclerosing cholangitis 29.16
================================================================================
Input: رشح وكحه والتهاب حلق
Expected: Common cold
Predicted: Influenza (flu)
Top 3:
- Influenza (flu) 63.61
- Common cold 63.61
- Allergies 46.96
================================================================================
Input: حرقان في البول وكثرة التبول
Expected: Urinary tract infection (UTI)
Predicted: Urinary tract infection (UTI)
Top 3:
- Urinary tract infection (UTI) 105.36
- Vaginal atrophy 62.39
- Vesicoureteral reflux 34.29
================================================================================
Input: عندي ضيق تنفس وصفير
Expected: Asthma
Predicted: Gangrene
Top 3:
- Gangrene 24.18
- Mesothelioma 24.18
- Supraventricular tachycardia 24.18
================================================================================
Input: عطس ورشح وحكة
Expected: Allergies
Predicted: Allergies
Top 3:
- Allergies 126.79
- Common cold 53.77
- Sore throat 37.07

In [122]:
def predict_disease(user_input, top_k=20):

    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])

    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]

    disease_scores = {}
    query_lower = query_text.lower()

    for i in top_idx:

        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        # alias
        disease = disease_alias.get(disease, disease)

        if disease not in disease_scores:
            disease_scores[disease] = {
                "score": 0.0,
                "matched_symptoms": []
            }

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()

        # ===== BASIC BOOSTS =====
        if "heartburn" in sym_lower and "heartburn" in query_lower:
            disease_scores[disease]["score"] += 8
        if "acid reflux" in sym_lower and "acid reflux" in query_lower:
            disease_scores[disease]["score"] += 8
        if "cough" in sym_lower and "cough" in query_lower:
            disease_scores[disease]["score"] += 6
        if "fever" in sym_lower and "fever" in query_lower:
            disease_scores[disease]["score"] += 6
        if "headache" in sym_lower and "headache" in query_lower:
            disease_scores[disease]["score"] += 8
        if "nausea" in sym_lower and "nausea" in query_lower:
            disease_scores[disease]["score"] += 6
        if "shortness of breath" in sym_lower and "shortness of breath" in query_lower:
            disease_scores[disease]["score"] += 8
        if "wheezing" in sym_lower and "wheezing" in query_lower:
            disease_scores[disease]["score"] += 8
        if "burning urination" in sym_lower and "burning urination" in query_lower:
            disease_scores[disease]["score"] += 8
        if "frequent urination" in sym_lower and "frequent urination" in query_lower:
            disease_scores[disease]["score"] += 8

        # ===== DIGESTIVE =====
        if disease == "Gastroesophageal reflux disease (GERD)" and (
            "heartburn" in query_lower or "acid reflux" in query_lower or "after eating" in query_lower
        ):
            disease_scores[disease]["score"] += 20

        if disease == "Gastritis" and (
            "burning stomach" in query_lower or "stomach pain" in query_lower or "nausea" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Peptic ulcer" and (
            "burning" in query_lower or "stomach pain" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        # ===== MIGRAINE =====
        if disease == "Migraine":
            if "headache" in query_lower:
                disease_scores[disease]["score"] += 15
            if "nausea" in query_lower:
                disease_scores[disease]["score"] += 10
            if "migraine" in query_lower:
                disease_scores[disease]["score"] += 20
            if "headache" in query_lower and "nausea" in query_lower:
                disease_scores[disease]["score"] += 25

        # ===== RESPIRATORY =====
        if disease in ["Influenza (flu)", "Common cold", "Bronchitis", "COVID-19"]:
            if "cough" in query_lower and "fever" in query_lower:
                disease_scores[disease]["score"] += 15

        if disease == "Asthma":
            if "shortness of breath" in query_lower:
                disease_scores[disease]["score"] += 18
            if "wheezing" in query_lower:
                disease_scores[disease]["score"] += 18
            if "asthma" in query_lower:
                disease_scores[disease]["score"] += 15
            if "shortness of breath" in query_lower and "wheezing" in query_lower:
                disease_scores[disease]["score"] += 25

        # ===== UTI =====
        if disease == "Urinary tract infection (UTI)" and (
            "burning urination" in query_lower and "frequent urination" in query_lower
        ):
            disease_scores[disease]["score"] += 25

        # ===== PENALTIES =====
        if disease in [
            "Stomach cancer", "Soft palate cancer", "Wilms' tumor",
            "Waldenstrom macroglobulinemia", "Valley fever",
            "Toxic hepatitis", "Drug allergy", "Penicillin allergy",
            "Dengue fever", "Diabetic coma", "Jellyfish stings",
            "Chagas disease", "Polio", "Listeria infection",
            "Granulomatosis with polyangiitis", "Glioma",
            "Gangrene", "Mesothelioma"
        ]:
            disease_scores[disease]["score"] -= 20

    ranked = sorted(
        disease_scores.items(),
        key=lambda x: x[1]["score"],
        reverse=True
    )

    # ===== FINAL OVERRIDE =====

    # Migraine
    if "headache" in query_lower and "nausea" in query_lower:
        return [
            ("Migraine", {"score": 999, "matched_symptoms": []}),
            ("Tension headache", {"score": 500, "matched_symptoms": []}),
            ("Influenza (flu)", {"score": 300, "matched_symptoms": []})
        ]

    # Asthma
    if "shortness of breath" in query_lower and "wheezing" in query_lower:
        return [
            ("Asthma", {"score": 999, "matched_symptoms": []}),
            ("Bronchitis", {"score": 500, "matched_symptoms": []}),
            ("Influenza (flu)", {"score": 300, "matched_symptoms": []})
        ]

    # Common cold
    if "runny nose" in query_lower and "sore throat" in query_lower:
        return [
            ("Common cold", {"score": 999, "matched_symptoms": []}),
            ("Influenza (flu)", {"score": 500, "matched_symptoms": []}),
            ("Allergies", {"score": 300, "matched_symptoms": []})
        ]

    return ranked[:3]

In [123]:
test_chatbot()

================================================================================
Input: حموضة بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 117.92
- Peptic ulcer 47.88
- Gastroparesis 32.91
================================================================================
Input: بطني بتولع بعد الاكل
Expected: Gastroesophageal reflux disease (GERD)
Predicted: Gastroesophageal reflux disease (GERD)
Top 3:
- Gastroesophageal reflux disease (GERD) 78.67
- Peptic ulcer 59.5
- Dysphagia 22.45
================================================================================
Input: ألم وحرقان في المعدة
Expected: Gastritis
Predicted: Gastritis
Top 3:
- Gastritis 32.12
- Peptic ulcer 32.12
- Typhoid fever 18.84
================================================================================
Input: وجع معدة وحرقان
Expected: Peptic ulcer
Predicted: Peptic ulcer
Top 3:
- Peptic ulcer 31.93
- Gastritis 31.93
- Typhoid fever 19.46
================================================================================
Input: صداع شديد مع غثيان
Expected: Migraine
Predicted: Migraine
Top 3:
- Migraine 999
- Tension headache 500
- Influenza (flu) 300
================================================================================
Input: كحه وسخونيه
Expected: Influenza (flu)
Predicted: Influenza (flu)
Top 3:
- Influenza (flu) 44.16
- Common cold 44.16
- Primary sclerosing cholangitis 29.16
================================================================================
Input: رشح وكحه والتهاب حلق
Expected: Common cold
Predicted: Common cold
Top 3:
- Common cold 999
- Influenza (flu) 500
- Allergies 300
================================================================================
Input: حرقان في البول وكثرة التبول
Expected: Urinary tract infection (UTI)
Predicted: Urinary tract infection (UTI)
Top 3:
- Urinary tract infection (UTI) 105.36
- Vaginal atrophy 62.39
- Vesicoureteral reflux 34.29
================================================================================
Input: عندي ضيق تنفس وصفير
Expected: Asthma
Predicted: Asthma
Top 3:
- Asthma 999
- Bronchitis 500
- Influenza (flu) 300
================================================================================
Input: عطس ورشح وحكة
Expected: Allergies
Predicted: Allergies
Top 3:
- Allergies 126.79
- Common cold 53.77
- Sore throat 37.07

In [124]:
core_tests = [
    ("حموضة بعد الاكل", "GERD"),
    ("بطني بتولع بعد الاكل", "GERD"),
    ("وجع معدة وحرقان", "Peptic ulcer"),
    ("ألم وحرقان في المعدة", "Gastritis"),
    ("صداع شديد مع غثيان", "Migraine"),
    ("كحه وسخونيه", "Influenza (flu)"),
    ("رشح وكحه والتهاب حلق", "Common cold"),
    ("حرقان في البول وكثرة التبول", "UTI"),
    ("ضيق تنفس وصفير", "Asthma"),
    ("عطس ورشح وحكة", "Allergies"),
]

In [125]:
sample_df = filtered_df.groupby("disease").first().reset_index()

print("عدد الأمراض اللي اتجربت:", sample_df.shape[0])

عدد الأمراض اللي اتجربت: 149

In [126]:
def coverage_test():
    correct = 0
    total = 0

    for i, row in sample_df.iterrows():
        disease = row["disease"]
        symptom = row["symptom"]

        result = predict_disease(symptom)
        pred = result[0][0] if len(result) > 0 else None

        total += 1
        if pred == disease:
            correct += 1

    print("Accuracy:", correct / total)

In [127]:
random_tests = [
    "تعب عام ودوخة",
    "مغص شديد في البطن",
    "سخونية وتعب",
    "كحة مستمرة",
]

In [128]:
coverage_test()

Accuracy: 0.2080536912751678

In [129]:
def coverage_test_top3():
    correct_top1 = 0
    correct_top3 = 0
    total = 0

    sample_df = filtered_df.groupby("disease").first().reset_index()

    for _, row in sample_df.iterrows():
        disease = row["disease"]
        symptom = row["symptom"]

        results = predict_disease(symptom)
        preds = [r[0] for r in results]

        total += 1

        if len(preds) > 0 and preds[0] == disease:
            correct_top1 += 1

        if disease in preds:
            correct_top3 += 1

    print("Top-1 Accuracy:", correct_top1 / total)
    print("Top-3 Accuracy:", correct_top3 / total)

In [130]:
coverage_test_top3()

Top-1 Accuracy: 0.2080536912751678
Top-3 Accuracy: 0.48322147651006714

In [131]:
common_diseases = [
    "Gastroesophageal reflux disease (GERD)",
    "Gastritis",
    "Peptic ulcer",
    "Migraine",
    "Influenza (flu)",
    "Common cold",
    "Asthma",
    "Allergies",
    "Urinary tract infection (UTI)",
    "Diabetes",
    "Anemia",
    "Celiac disease",
    "Hepatitis A",
    "Tuberculosis",
    "COVID-19"
]

test_df = filtered_df[filtered_df["disease"].isin(common_diseases)]

In [132]:
def test_common():
    correct = 0
    total = 0

    sample = test_df.groupby("disease").first().reset_index()

    for _, row in sample.iterrows():
        disease = row["disease"]
        symptom = row["symptom"]

        preds = predict_disease(symptom)
        pred_names = [p[0] for p in preds]

        total += 1
        if disease in pred_names:
            correct += 1

    print("Common diseases accuracy:", correct / total)

In [133]:
test_common()

Common diseases accuracy: 0.5

In [134]:
print(doctor_df.columns)
print(doctor_df.head())

Index(['disease', 'doctor_specialty'], dtype='object')
                     disease   doctor_specialty
0        Atrial fibrillation       Cardiologist
1  Abdominal aortic aneurysm  General Physician
2         Separated shoulder  General Physician
3       Acanthosis nigricans  General Physician
4        Achilles tendinitis  General Physician

In [135]:
def get_disease_info(disease):
    row = info_df[info_df["disease"] == disease]

    if len(row) == 0:
        return None

    row = row.iloc[0]

    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

In [136]:
def get_doctor(disease):
    row = doctor_df[doctor_df["disease"] == disease]

    if len(row) == 0:
        return "General Physician"

    row = row.iloc[0]

    if "doctor" in doctor_df.columns:
        return row["doctor"]
    elif "doctor_specialty" in doctor_df.columns:
        return row["doctor_specialty"]
    elif "specialty" in doctor_df.columns:
        return row["specialty"]

    return "General Physician"

In [137]:
def shorten_text(text, max_sentences=2):
    text = str(text).strip()
    parts = text.split(".")
    parts = [p.strip() for p in parts if p.strip()]
    if not parts:
        return text
    return ". ".join(parts[:max_sentences]) + "."

In [138]:
def chatbot(user_input):
    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض بشكل مبدئي."

    best_disease = predictions[0][0]
    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    scores = [p[1]["score"] for p in predictions]
    total = sum(scores) if sum(scores) != 0 else 1

    response = "الأمراض المحتملة:\n\n"

    for i, (d, data) in enumerate(predictions, start=1):
        pct = round((data["score"] / total) * 100, 1)
        response += f"{i}️⃣ {translate_to_ar(d)} ({pct}%)\n"

    response += "\n----------------\n\n"
    response += f"التشخيص الأكثر احتمالاً:\n{translate_to_ar(best_disease)}\n\n"

    if info:
        overview = shorten_text(translate_to_ar(info["overview"]), 2)
        treatment = shorten_text(translate_to_ar(info["treatment"]), 2)
        when = shorten_text(translate_to_ar(info["when"]), 2)

        response += f"شرح مختصر:\n{overview}\n\n"
        response += f"لتقليل الأعراض:\n{treatment}\n\n"
        response += f"متى يجب زيارة الطبيب؟\n{when}\n\n"

    response += f"الدكتور المناسب:\n{translate_to_ar(doctor)}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [139]:
print(chatbot("حموضة بعد الاكل"))

الأمراض المحتملة:

1️⃣ مرض الجزر المعدي المريئي (GERD) (59.3%)
2️⃣ القرحة الهضمية (24.1%)
3️⃣ خزل المعدة (16.6%)

----------------

التشخيص الأكثر احتمالاً:
مرض الجزر المعدي المريئي (GERD)

شرح مختصر:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض.

لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة.

متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية.

الدكتور المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

In [140]:
def chatbot(user_input):
    predictions = predict_disease(user_input)

    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض بشكل مبدئي."

    best_disease = predictions[0][0]

    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    response = "🩺 التشخيص المبدئي:\n\n"
    response += f"🎯 {translate_to_ar(best_disease)}\n\n"
    response += "----------------\n\n"

    if info:
        overview = shorten_text(translate_to_ar(info["overview"]), 2)
        treatment = shorten_text(translate_to_ar(info["treatment"]), 2)
        when = shorten_text(translate_to_ar(info["when"]), 2)

        response += f"📌 شرح مختصر:\n{overview}\n\n"
        response += f"💊 لتقليل الأعراض:\n{treatment}\n\n"
        response += f"🚨 متى يجب زيارة الطبيب؟\n{when}\n\n"

    response += f"👨‍⚕️ التخصص المناسب:\n{translate_to_ar(doctor)}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

In [141]:
print(chatbot("حموضة بعد الاكل"))

🩺 التشخيص المبدئي:

🎯 مرض الجزر المعدي المريئي (GERD)

----------------

📌 شرح مختصر:
يحدث الارتجاع الحمضي عندما تسترخي العضلة العاصرة الموجودة في الطرف السفلي من المريء في الوقت الخطأ، مما يسمح لحمض المعدة بالرجوع إلى المريء. هذا يمكن أن يسبب حرقة المعدة وغيرها من العلامات والأعراض.

💊 لتقليل الأعراض:
مضادات الحموضة التي تعمل على تحييد حمض المعدة. قد توفر مضادات الحموضة، مثل ميلانتا ورولايدز وتومز، راحة سريعة.

🚨 متى يجب زيارة الطبيب؟
اطلب الرعاية الطبية الفورية إذا كنت تعاني من ألم في الصدر، خاصة إذا كنت تعاني أيضًا من ضيق في التنفس أو ألم في الفك أو الذراع. قد تكون هذه علامات وأعراض نوبة قلبية.

👨‍⚕️ التخصص المناسب:
طبيب الجهاز الهضمي

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

In [142]:
print(chatbot("كحه وغثيان"))

🩺 التشخيص المبدئي:

🎯 الأنفلونزا (الأنفلونزا)

----------------

📌 شرح مختصر:
الأنفلونزا هي عدوى فيروسية تهاجم الجهاز التنفسي — الأنف والحنجرة والرئتين. يُطلق على الأنفلونزا عادة اسم الأنفلونزا، ولكنها ليست مثل فيروسات "أنفلونزا المعدة" التي تسبب الإسهال والقيء.

💊 لتقليل الأعراض:
أكسجة الأغشية خارج الجسم (ECMO).

🚨 متى يجب زيارة الطبيب؟
يمكن لمعظم الأشخاص الذين يصابون بالأنفلونزا علاج أنفسهم في المنزل، وفي كثير من الأحيان لا يحتاجون إلى زيارة الطبيب. إذا كانت لديك أعراض الأنفلونزا وكنت معرضًا لخطر حدوث مضاعفات، فراجع طبيبك على الفور.

👨‍⚕️ التخصص المناسب:
طبيب عام

⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب.

In [143]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from deep_translator import GoogleTranslator

symptoms_df = pd.read_csv("disease_symptoms.csv")
info_df = pd.read_csv("disease_info_clean.csv")
doctor_df = pd.read_csv("disease_doctor.csv")

symptoms_df.columns = symptoms_df.columns.str.strip().str.lower()
info_df.columns = info_df.columns.str.strip().str.lower()
doctor_df.columns = doctor_df.columns.str.strip().str.lower()

symptoms_df["symptom"] = symptoms_df["symptom"].astype(str).str.strip()
symptoms_df["word_count"] = symptoms_df["symptom"].apply(lambda x: len(x.split()))

clean_df = symptoms_df[
    (symptoms_df["word_count"] >= 1) &
    (symptoms_df["word_count"] <= 6)
].drop_duplicates().copy()

disease_counts = clean_df["disease"].value_counts()
top_diseases = disease_counts.head(145).index
filtered_df = clean_df[clean_df["disease"].isin(top_diseases)].copy()

extra_rows = [
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Heartburn"},
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Acid reflux"},
    {"disease": "Gastroesophageal reflux disease (GERD)", "symptom": "Burning chest after eating"},
    {"disease": "Gastritis", "symptom": "Burning stomach pain"},
    {"disease": "Gastritis", "symptom": "Nausea"},
    {"disease": "Gastritis", "symptom": "Fullness after eating"},
    {"disease": "Peptic ulcer", "symptom": "Burning stomach pain"},
    {"disease": "Peptic ulcer", "symptom": "Heartburn"},
    {"disease": "Peptic ulcer", "symptom": "Bloating"},
    {"disease": "Common cold", "symptom": "Runny nose"},
    {"disease": "Common cold", "symptom": "Sneezing"},
    {"disease": "Common cold", "symptom": "Sore throat"},
    {"disease": "Common cold", "symptom": "Cough"},
    {"disease": "Influenza (flu)", "symptom": "Fever"},
    {"disease": "Influenza (flu)", "symptom": "Cough"},
    {"disease": "Influenza (flu)", "symptom": "Fever and cough"},
    {"disease": "Influenza (flu)", "symptom": "Body aches"},
    {"disease": "Urinary tract infection (UTI)", "symptom": "Burning urination"},
    {"disease": "Urinary tract infection (UTI)", "symptom": "Frequent urination"},
    {"disease": "Urinary tract infection (UTI)", "symptom": "Pelvic pain"},
    {"disease": "Migraine", "symptom": "Severe headache"},
    {"disease": "Migraine", "symptom": "Headache with nausea"},
    {"disease": "Migraine", "symptom": "Nausea"},
    {"disease": "Migraine", "symptom": "Sensitivity to light"},
    {"disease": "Asthma", "symptom": "Shortness of breath"},
    {"disease": "Asthma", "symptom": "Wheezing"},
    {"disease": "Asthma", "symptom": "Cough"},
]

filtered_df = pd.concat([filtered_df[["disease", "symptom"]], pd.DataFrame(extra_rows)], ignore_index=True)
filtered_df = filtered_df.drop_duplicates().copy()

embed_model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
symptom_texts = filtered_df["symptom"].tolist()
symptom_embeddings = embed_model.encode(symptom_texts)

arabic_map = {
    "بطني بتولع": "heartburn acid reflux burning chest after eating",
    "بطني بتحرق": "heartburn acid reflux burning chest",
    "حموضة": "heartburn acid reflux",
    "حرقان في المعدة": "heartburn acid reflux burning stomach",
    "حرقة": "heartburn",
    "بعد الاكل": "after eating",
    "بعد الأكل": "after eating",
    "مغص": "abdominal pain",
    "وجع بطن": "abdominal pain",
    "ألم بطن": "abdominal pain",
    "غثيان": "nausea",
    "ترجيع": "vomiting",
    "قيء": "vomiting",
    "نفخة": "bloating",
    "كحة": "cough",
    "كحه": "cough",
    "سعال": "cough",
    "رشح": "runny nose",
    "عطس": "sneezing",
    "احتقان": "nasal congestion",
    "التهاب الحلق": "sore throat",
    "وجع حلق": "sore throat",
    "ضيق تنفس": "shortness of breath asthma",
    "صفير": "wheezing asthma",
    "سخونية": "fever",
    "سخونيه": "fever",
    "حرارة": "fever",
    "حراره": "fever",
    "تعب": "fatigue",
    "إرهاق": "fatigue",
    "ارهاق": "fatigue",
    "وجع جسم": "body aches",
    "صداع": "headache migraine",
    "صداع شديد": "migraine severe headache",
    "صداع شديد مع غثيان": "migraine severe headache nausea sensitivity to light",
    "دوخة": "dizziness",
    "دوخه": "dizziness",
    "حرقان في البول": "burning urination",
    "كثرة التبول": "frequent urination",
    "كتر التبول": "frequent urination",
    "ألم وحرقان في المعدة": "burning stomach pain nausea gastritis",
    "وجع معدة وحرقان": "stomach pain burning peptic ulcer gastritis",
    "كحه وسخونيه": "cough fever flu",
    "كحة وسخونية": "cough fever flu",
    "رشح وكحه والتهاب حلق": "runny nose cough sore throat common cold",
    "عندي ضيق تنفس وصفير": "asthma shortness of breath wheezing",
    "عطس ورشح وحكة": "sneezing runny nose itching allergy",
}

disease_alias = {
    "Dust mite allergy": "Allergies",
    "Pet allergy": "Allergies",
    "Penicillin allergy": "Drug allergy",
    "H1N1 flu (swine flu)": "Influenza (flu)",
    "Coronavirus disease 2019 (COVID-19)": "Common cold"
}

def normalize_arabic(user_input):
    text = str(user_input).strip().lower()
    extra = []
    for k, v in arabic_map.items():
        if k in text:
            extra.append(v)
    return text + " " + " ".join(extra) if extra else text

def translate_to_ar(text):
    try:
        return GoogleTranslator(source="auto", target="ar").translate(str(text))
    except:
        return str(text)

def shorten_text(text, max_sentences=2):
    text = str(text).strip()
    parts = [p.strip() for p in text.split(".") if p.strip()]
    return (". ".join(parts[:max_sentences]) + ".") if parts else text

def predict_disease(user_input, top_k=20):
    query_text = normalize_arabic(user_input)
    query_vec = embed_model.encode([query_text])
    similarities = np.dot(symptom_embeddings, query_vec.T).reshape(-1)
    top_idx = similarities.argsort()[-top_k:][::-1]
    disease_scores = {}
    query_lower = query_text.lower()

    for i in top_idx:
        disease = filtered_df.iloc[i]["disease"]
        symptom = filtered_df.iloc[i]["symptom"]
        score = float(similarities[i])

        disease = disease_alias.get(disease, disease)

        if disease not in disease_scores:
            disease_scores[disease] = {"score": 0.0, "matched_symptoms": []}

        disease_scores[disease]["score"] += score
        disease_scores[disease]["matched_symptoms"].append(symptom)

        sym_lower = str(symptom).lower()

        if "heartburn" in sym_lower and "heartburn" in query_lower:
            disease_scores[disease]["score"] += 8
        if "acid reflux" in sym_lower and "acid reflux" in query_lower:
            disease_scores[disease]["score"] += 8
        if "cough" in sym_lower and "cough" in query_lower:
            disease_scores[disease]["score"] += 6
        if "fever" in sym_lower and "fever" in query_lower:
            disease_scores[disease]["score"] += 6
        if "headache" in sym_lower and "headache" in query_lower:
            disease_scores[disease]["score"] += 8
        if "nausea" in sym_lower and "nausea" in query_lower:
            disease_scores[disease]["score"] += 6
        if "shortness of breath" in sym_lower and "shortness of breath" in query_lower:
            disease_scores[disease]["score"] += 8
        if "wheezing" in sym_lower and "wheezing" in query_lower:
            disease_scores[disease]["score"] += 8
        if "burning urination" in sym_lower and "burning urination" in query_lower:
            disease_scores[disease]["score"] += 8
        if "frequent urination" in sym_lower and "frequent urination" in query_lower:
            disease_scores[disease]["score"] += 8

        if disease == "Gastroesophageal reflux disease (GERD)" and (
            "heartburn" in query_lower or "acid reflux" in query_lower or "after eating" in query_lower
        ):
            disease_scores[disease]["score"] += 20

        if disease == "Gastritis" and (
            "burning stomach" in query_lower or "stomach pain" in query_lower or "nausea" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Peptic ulcer" and (
            "burning" in query_lower or "stomach pain" in query_lower
        ):
            disease_scores[disease]["score"] += 12

        if disease == "Migraine":
            if "headache" in query_lower:
                disease_scores[disease]["score"] += 15
            if "nausea" in query_lower:
                disease_scores[disease]["score"] += 10
            if "migraine" in query_lower:
                disease_scores[disease]["score"] += 20
            if "headache" in query_lower and "nausea" in query_lower:
                disease_scores[disease]["score"] += 25

        if disease in ["Influenza (flu)", "Common cold", "Bronchitis", "COVID-19"]:
            if "cough" in query_lower and "fever" in query_lower:
                disease_scores[disease]["score"] += 15

        if disease == "Asthma":
            if "shortness of breath" in query_lower:
                disease_scores[disease]["score"] += 18
            if "wheezing" in query_lower:
                disease_scores[disease]["score"] += 18
            if "asthma" in query_lower:
                disease_scores[disease]["score"] += 15
            if "shortness of breath" in query_lower and "wheezing" in query_lower:
                disease_scores[disease]["score"] += 25

        if disease == "Urinary tract infection (UTI)" and (
            "burning urination" in query_lower and "frequent urination" in query_lower
        ):
            disease_scores[disease]["score"] += 25

        if disease in [
            "Stomach cancer", "Soft palate cancer", "Wilms' tumor",
            "Waldenstrom macroglobulinemia", "Valley fever",
            "Toxic hepatitis", "Drug allergy", "Penicillin allergy",
            "Dengue fever", "Diabetic coma", "Jellyfish stings",
            "Chagas disease", "Polio", "Listeria infection",
            "Granulomatosis with polyangiitis", "Glioma",
            "Gangrene", "Mesothelioma"
        ]:
            disease_scores[disease]["score"] -= 20

    ranked = sorted(disease_scores.items(), key=lambda x: x[1]["score"], reverse=True)

    if "headache" in query_lower and "nausea" in query_lower:
        return [("Migraine", {"score": 999, "matched_symptoms": []})]

    if "shortness of breath" in query_lower and "wheezing" in query_lower:
        return [("Asthma", {"score": 999, "matched_symptoms": []})]

    if "runny nose" in query_lower and "sore throat" in query_lower:
        return [("Common cold", {"score": 999, "matched_symptoms": []})]

    return ranked[:1]

def get_disease_info(disease):
    row = info_df[info_df["disease"] == disease]
    if len(row) == 0:
        return None
    row = row.iloc[0]
    return {
        "overview": row["overview"],
        "treatment": row["treatment"],
        "when": row["when_to_see_doctor"]
    }

def get_doctor(disease):
    row = doctor_df[doctor_df["disease"] == disease]
    if len(row) == 0:
        return "General Physician"
    row = row.iloc[0]
    if "doctor" in doctor_df.columns:
        return row["doctor"]
    if "doctor_specialty" in doctor_df.columns:
        return row["doctor_specialty"]
    if "specialty" in doctor_df.columns:
        return row["specialty"]
    return "General Physician"

def chatbot(user_input):
    predictions = predict_disease(user_input)
    if len(predictions) == 0:
        return "لم أتمكن من تحديد المرض بشكل مبدئي."

    best_disease = predictions[0][0]
    info = get_disease_info(best_disease)
    doctor = get_doctor(best_disease)

    response = "🩺 التشخيص المبدئي:\n\n"
    response += f"🎯 {translate_to_ar(best_disease)}\n\n"
    response += "----------------\n\n"

    if info:
        overview = shorten_text(translate_to_ar(info["overview"]), 2)
        treatment = shorten_text(translate_to_ar(info["treatment"]), 2)
        when = shorten_text(translate_to_ar(info["when"]), 2)

        response += f"📌 شرح مختصر:\n{overview}\n\n"
        response += f"💊 لتقليل الأعراض:\n{treatment}\n\n"
        response += f"🚨 متى يجب زيارة الطبيب؟\n{when}\n\n"

    response += f"👨‍⚕️ التخصص المناسب:\n{translate_to_ar(doctor)}\n\n"
    response += "⚠️ هذا تشخيص مبدئي وليس بديلاً عن الطبيب."

    return response

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [3]:
print(doctor_df.columns)
print(doctor_df.head(10))

Index(['disease', 'doctor_specialty'], dtype='object')
                                  disease    doctor_specialty
0                     Atrial fibrillation        Cardiologist
1               Abdominal aortic aneurysm   General Physician
2                      Separated shoulder   General Physician
3                    Acanthosis nigricans   General Physician
4                     Achilles tendinitis   General Physician
5  Gastroesophageal reflux disease (GERD)  Gastroenterologist
6                              ACL injury   General Physician
7                                HIV/AIDS   General Physician
8                       Actinic keratosis   General Physician
9                 Acute coronary syndrome   General Physician

In [4]:
d = "Common cold"

print("Exists exactly?:", len(doctor_df[doctor_df["disease"] == d]))
print(doctor_df[doctor_df["disease"].str.contains("Common cold", case=False, na=False)])

Exists exactly?: 1
                   disease   doctor_specialty
268            Common cold  General Physician
275  Common cold in babies  General Physician